### ISSUE TITLE
Add install instructions [Feature request]

### ISSUE THREAD

**Issue by EarthlingDavey** [fwestenberg/reolink_dev#105]
Hi, I'm new to HA, I have core installed on a Pi3+ and this is my first custom component.

I think some install instructions would really help some newbies like me. 

I can only account for install on core, may I suggest the following..

To install this integration on Home Assistant core

1. Login as the homeassistant user
2. Go to the config dir (your directory that contains configuration.yaml)
3. Make the custom_components folder if it doesn't exist already.
4. Clone this project to a tmp directory
5. Copy custom_components/reolink_dev from the temp directory to your custom_components folder
6. Restart the homeassistant service

The following commands can be used

```
sudo -u homeassistant -H -s
cd ~/.homeassistant
mkdir -p custom_components
git clone https://github.com/fwestenberg/reolink_dev.git /tmp/reolink_dev
cp -r  /tmp/reolink_dev/custom_components/reolink_dev/ custom_components/reolink_dev
sudo systemctl restart home-assistant@homeassistant
```

To add a camera from your Home Assistant admin page.

- Click: Configuration > Integrations > Add Integration > Reolink IP camera
- Enter details for your camera.
- The camera will now be available as an entity.

**Comment by fwestenberg** [comment]
Hi @EarthlingDavey, 

Thanks for your message. I just don't think those instructions belong here. Installing custom components is already described on different places and also depend on your installation. Beside that, you can just install HACS (this is a HACS component!) and install from the UI. So just follow [this](https://hacs.xyz/docs/installation/manual) guide!

**Comment by EarthlingDavey** [comment]
Sure, I can only speak from my experience as a HA newb. 

May I still suggest that you add some _**brief**_ install and usage documentation. I expect it would be helpful for others.

**Comment by xdago117x** [comment]
> To add a camera from your Home Assistant admin page.

    Click: Configuration > Integrations > Add Integration > Reolink IP camera
    Enter details for your camera.
    The camera will now be available as an entity.

Thats exactly what I was missing, if you add this to your readme it will help a lot of ppl out there ;)
Anyways, so many thanks for this great plugin!

Greetz
Tom
