### ISSUE TITLE
Are you going to add the support of E1Pro?

### ISSUE THREAD

**Issue by Spirituss** [fwestenberg/reolink_dev#106]
Hello!

Do you have plans to add support of E1 Pro? It would be great!

**Comment by fwestenberg** [comment]
I think the E1 pro has no webUI right?

**Comment by Spirituss** [comment]
> I think the E1 pro has no webUI right?

Yes, it can be configured only via it's application. But Synology Surveillance Station, for example, could work with the camera, why this component can't?

**Comment by fwestenberg** [comment]
The thing is, if the API is completely different from the other camera's nothing of this integration will work. I believe some other E1 users already figured out it will not work. You can in this case better use the generic camera integration in HA.

**Comment by fwestenberg** [comment]
You can however try and open the webbrowser, navigate to your camera and check if it has the CGI API. Just debug in the browser and check what the calls look like.

**Comment by Spirituss** [comment]
> The thing is, if the API is completely different from the other camera's nothing of this integration will work. I believe some other E1 users already figured out it will not work. You can in this case better use the generic camera integration in HA.

Unfortunately, generic camera integration doesn't provide the ability to control PTZ of Reolink E1 Pro. I saw such services in your component, that's why I would like to use it with my camera.

**Comment by Spirituss** [comment]
> You can however try and open the webbrowser, navigate to your camera and check if it has the CGI API. Just debug in the browser and check what the calls look like.

There is a CGI API for E1 Pro (see below). Hope, it will help you to develop this useful component.
[CGI_command (1).pdf](https://github.com/fwestenberg/reolink_dev/files/5711689/CGI_command.1.pdf)

**Comment by fwestenberg** [comment]
The API you mention is almost the same, the idea is exactly the same. The main difference is, it's not async. So for Home Assistant less optimized.

Also, I don't own a E1. You can send me a pull request jf you figure out what should be changed.

**Comment by fwestenberg** [comment]
There is another E1 issue available, I'll update there if anything changed!
