### ISSUE TITLE
E1 Zoom: Cannot get live camera view 

### ISSUE THREAD

**Issue by Uozzon** [fwestenberg/reolink_dev#107]
**Describe the bug**
I can get the preview of the camera with a picture element, but clicking I cannot get the live view

**To Reproduce**
After creating a card like this:
```
entity: camera.sala
type: picture-entity
```
click to have the preview and get a broken link.
Inspecting the link, it seems correct (an old version of the Reolink add-on did not have the token, but this one has it):
/api/camera_proxy_stream/camera.sala?token=d7cb76d0dfb0784e2704735524a607b08a167ee20f5bb143f726b681a4a6293f

**Expected behavior**
I expected to see a live view of the camera, as I can get with all cameras.

**Environment:**
Please provide useful information about your environment, like:
 - Home Assistant version: 2020.12.1 (same bug with older versions) 
 - Reolink camera model: Reolink E1 Zoom
 - Camera firmware number: v3.0.0.65_20071008

**Comment by fwestenberg** [comment]
Hi @Uozzon,

I don't own an E1 kind of camera. But other users reported it's not working with the Reolink integration and so it's not supported. If you find a way, please let me know. The idea is, the camera should have to Reolink cgi at least (web UI, reacheble from the web browser)...

**Comment by Uozzon** [comment]
Hi @fwestenberg,

thanks for the quick answer.
Sorry, I didn't see the E1 Zoom version in the unsupported list, and since it actually "works" (apart from the above bug) I supposed the Zoom version was supported :)

Anyway I can confirm that my Reolink E1 Zoom:
- can display the preview
- the motion binary_sensor is perfectly working
- the ptz service is also perfectly working.
I'll check also other functionalities and be back confirming if they work.

As far as the bug, I should dig a little more into the code to check why the live view is not available.
In an older version of the integration it seemed an auth-token problem (there was an empty token in the URL),
now the token is there but the link is broken.
I'll let you know if I find some information.

Anyway with your Reolink cam you can create a picture-entity card having also le live view ?

**Comment by fwestenberg** [comment]
Can you give an example of a working url for streaming? You can test this with VLC for example.

**Comment by copilador** [comment]
Hi, 
The same problem with camera:
 RLC-410-5MP
 Firmware number: v3.0.0.65_20071000

Home Assistant 2020.12.1
ver. 0.9

**Comment by marcello9** [comment]
I just installed one of these E1 Zoom camera's today, and was a bit scared it would not work but it appears I get both the 10 second stills on UI and when I click on it I get live view... the live view is a bit big etc (I use a 4k screen..) but I did not look into any possible options just yet...
All I did was install the repo, clear browser cache to make the integration show up, add integration, add camera details and added one entity to my main view... Thanks @fwestenberg for making this integration !

**Comment by fwestenberg** [comment]
Great to hear this! Please keep us posted about your experiences!

**Comment by adn34** [comment]
Just here to confirm it does work for me with the E1 Zoom out of the box as well, streaming included. 

Firmware version is v3.0.0.112_20101508

Thank you very much for this integration!

**Comment by ed-holland** [comment]
I also have a E1-Zoom with this issue (Firmware: v3.0.0.136_20121163) which is not showing the stream.
Same issue also with a RLC-511W (Firmware: v3.0.0.136_20121159).
I've tried with rmtp and rtsp.

FYI: PTZ id's (E1-Zoom) do not show up when using a guest account.

**Comment by ed-holland** [comment]
Inspect shows that the Camera Proxy is being called, but no stream is received.
I've installed HA in Supervised Mode. Maybe that is the difference.

**Comment by ed-holland** [comment]
I've been able to resolve it in my installation. Streaming needs to be enabled.
```
# Enable Streaming
stream:
```
If you enable pre-loading of the stream, it is immediately shown.

**Comment by fwestenberg** [comment]
Thanks @ed-holland!
