### ISSUE TITLE
Stream always on main

### ISSUE THREAD

**Issue by Eddie46848** [fwestenberg/reolink_dev#109]
**Describe the bug**
When selecting stream to sub it always remains on main. 
I've changed the settings for fluent on reolink app to the lowest to confirm this.

**To Reproduce**
Reboot still says the stream is sub, but it remains on main when viewing.
Causing the view in picture glance card to be really slow or not at all.

**Environment:**
 - Home Assistant version 2020.12.7
 - Reolink camera model RLC 410 5mp
 - Camera firmware number v3.0.0.136_20121100

**Comment by fwestenberg** [comment]
Are the camera setting different per stream? So in the webUI, how is it configured? What integration version do you use?

**Comment by Eddie46848** [comment]
V0.9
![Screenshot_20201220-111943](https://user-images.githubusercontent.com/67969969/102711950-59eab580-42b5-11eb-8c42-88c64438072b.jpg)

**Comment by fwestenberg** [comment]
You are right, thanks! I'll fix this asap. Just ran a test and my stream also doesn't change.

**Comment by andriej** [comment]
Same here, just have upgraded from old repo to new one (glad it's config flow, thanks!)
Although setting 'sub' shows 'sub' in Integrations, but in HA it opens in main.
Also in log file first time I set 'sub' and save change:
```
2020-12-21 04:00:42 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/config/custom_components/reolink_dev/__init__.py", line 113, in update_listener
await base.api.update_stream(entry.options[CONF_STREAM])
AttributeError: 'Api' object has no attribute 'update_stream'
2020-12-21 04:00:57 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/config/custom_components/reolink_dev/__init__.py", line 113, in update_listener
await base.api.update_stream(entry.options[CONF_STREAM])
AttributeError: 'Api' object has no attribute 'update_stream'
```

(for two cameras)

**Comment by fwestenberg** [comment]
Can you please update to v0.10 and let me know your experiences? Thanks!

**Comment by Eddie46848** [comment]
Hi
Yes it works perfectly now. Thanks.

**Comment by fwestenberg** [comment]
Thanks!
