### ISSUE TITLE
platform setup

### ISSUE THREAD

**Issue by xdago117x** [fwestenberg/reolink_dev#112]
Hi There,

since v0.8 I always get the following error in log
"The reolink_dev platform for the camera integration does not support platform setup. Please remove it from your config."
If I change back to v0.7 it works well, could you plz give any advice what to do?

Cam: RLC520
HA: 2020.12.7
config.yaml: 
camera:
  - platform: reolink_dev
    host: 192.168.0.220
    username: admin
    password: password
    name: Einfahrt main
    stream: main #main or sub (optional, default main)
    protocol: rtmp #rtmp or rtsp (optional, default rtmp)
    channel: 0
    scan_interval: 1 #(optional, default 30s)

Many thanks 
Tom

EDIT: Found out how to integrate the cam, sorry!

**Comment by fwestenberg** [comment]
No problem! Let me know your experiences please!

**Comment by xdago117x** [comment]
Hiho,

my experience? Its a great Addon, after I understand how to integrate my cam, its working pretty well, very good job !!
The only bad thing is the instructions. There is no description what to do after the plugin was installed via HACS ;)

Greetz
Tom

**Comment by pbaird** [comment]
What is the resolution? What changed, and should the yaml look now that platform is not supported?

**Comment by xdago117x** [comment]
Remove the whole camera from your yaml, restart HA, go to settings -> integrations -> reolink ip cam and set the camera up ;)

**Comment by pbaird** [comment]
wow!  I made an assumption that the configuration instructions would be for an individual camera, not my NVR, and didn't really pay attention to them.....  lesson learned!  Thanks for telling me this.
