### ISSUE TITLE
Not enable to create integration for RLC-410W

### ISSUE THREAD

**Issue by giangi007** [fwestenberg/reolink_dev#113]
**Describe the bug**
I'm not be able to integrate my RLC-410W in home assistant, I receive this message: Failed to connect with the camera

**To Reproduce**
2020-12-20 18:11:47 ERROR (MainThread) [reolink.camera_api] Error translating login response to json
2020-12-20 18:11:47 ERROR (MainThread) [reolink.camera_api] Error translating Reolink settings response
I install a E1 zoom with the same user and password without problem, but for RLC-410W nothing integration

**Expected behavior**
i'd like to integration my second camera

**Screenshots**

![image](https://user-images.githubusercontent.com/15632171/102719978-76a4de80-42f1-11eb-820f-68335b82538d.png)

**Environment:**

 - Home Assistant version: 2020.12.1
 - Reolink camera model: RLC -410W
 - Camera firmware number: Config Version v3.0.0.0
                                              Firmware Version v3.0.0.121_20111902

**Additional context**
Until update to 2020.12.1 the second camera works good

**Comment by fwestenberg** [comment]
Looks like a timeout error to me. How well is the connection?

**Comment by giangi007** [comment]
the connection is by wifi, the same as the E1 zoom (5,4 ghz). The web interface works.

Thanks

**Comment by fwestenberg** [comment]
But what does this say about speed? For example, does HD streaming run well?

**Comment by giangi007** [comment]
Hello, the HD streaming works correct by application and also by web interface. The image is fluid without interruption  and also the timestamp is correct and in real-time

**Comment by fwestenberg** [comment]
Can you please test with the latest (updated) version?

**Comment by giangi007** [comment]
Ho, I installed the nel versione and it workshop. Thank you for your help.

**Comment by fwestenberg** [comment]
Great to hear it workshop! Merry christmas!
