### ISSUE TITLE
Question: Starting from v0.8 it's no longer possible to use this in a core/pyvenv/Docker installation?

### ISSUE THREAD

**Issue by Jyx** [fwestenberg/reolink_dev#117]
Hi,

I think I know the answer, but still wanted to ask. I can see that starting from v0.8 things have changed quite a bit, the code, documentation etc. It looks like the only provided way after v0.8 is to pick it up via Integrations. I.e., for people who are running Home Assistant from a Python virtual env (pyvenv) etc, we're out of luck with recent versions and we have to stick with v0.7? I guess the answer is yes?

Btw, if you want a translation for Swedish (i.e., a `se.json` file), please let me know and I can send a PR for it.

// Regards
Joakim

**Comment by fwestenberg** [comment]
Hi Joakim,

I wasn't aware of this, so you can only use yaml config?
To make this work, I should add some things to the config_flow.yaml. Perhaps you can look into this? 
You're always welcome to add translations! I will add them to the next release.

**Comment by Jyx** [comment]
> I wasn't aware of this, so you can only use yaml config?

If you're referring to `configuration.yaml`, then the answer is yes. I started using HA this summer and decided to go with the simpler pyvenv setup. Since I have Reolink cameras (410) I searched and found your custom component. From there it was pretty straight forward, copy it to the `custom_components` folder and then add settings as described in your v0.7 `README.md` to my `configuration.yaml` file and then things worked. I've since then noticed that it hangs occasionally and therefore I went here again to see if recent updates had fixes for it. I tried the latest version, but things didn't work. After looking a bit more into the git history and seeing that you're aiming for official support and seeing that old instructions from the `README.md` had been removed, I concluded that the old v0.7 instructions (`configuration.yaml`) no longer applies and therefore support for simple pyvenv setup etc no longer are supported.

What I can answer is that if I try the "`Configuration > Integrations, click the button Add Integration > Reolink IP camera`" instructions from a pyvenv-setup, then you find no integrations and there is no way to add the link manually. In the fully fledged HA setup you can apparently do that by adding a custom repository (see [YouTube](https://youtu.be/LKeRNk-QbVg?t=776)). I.e., in pyvenv you have no "custom repositories" (not that I'm aware of at least).

Having said that, this got me thinking that if you get it accepted and merged officially, then it probably should show up in the Integrations in future HA releases even for pyvenv and similar, i.e., no matter how you're running HA. I.e., maybe this will get resolved by itself if I just wait a bit.

> To make this work, I should add some things to the config_flow.yaml. Perhaps you can look into this?

I'd be happy to do so, but I have no real experience with it. After thinking about it , it maybe a more generic issue and that is how to add custom integrations into a pyvenv installation similar to how you can do it from a fully fledged HA setup.

> You're always welcome to add translations! I will add them to the next release.

PR submitted as #118 and I can see that you already merged it, thanks!

**Comment by Jyx** [comment]
Some success since I wrote the above. I managed to install HACS and then via that I could get Reolink into the Integration. I can add a camera, but get stuck there, it's a webhook issue. I'm currently reading the other threads regarding webhook, http vs https etc. In any case. I think I've figured out an answer more or less, so I'm closing the ticket. Thanks for the feedback!

**Comment by fwestenberg** [comment]
Great to hear, and I am sure we'll succeed with the other issues too!
