### ISSUE TITLE
Integration not available/visible in HA

### ISSUE THREAD

**Issue by wrpooley** [fwestenberg/reolink_dev#121]
Hello.  I'm trying to install this integration and I am able to install the custom repository (reolink_dev).  Upon completing that step I see it "pending restart".  After restarting HA server MANY times I am still not able to add the integration through Configuration/Add integration.  It is not visible.  

Operating System
  Home Assistant OS 5.9
Core
  2020.12.1

thanks!

**Comment by spripe** [comment]
Following this, have the same trouble.
2020.12.1

**Comment by fwestenberg** [comment]
This has nothing to do with this integration. More likely your HA install or something. Some other user reported removing the browser cache helped.

**Comment by j0rdyk** [comment]
Hello @fwestenberg 

The same thing happens over here.
I tried searching in the integrations https://www.home-assistant.io/integrations/#search/reolink but nothing found.

Just tried clearing the cache, no solution for me. Anyone had the same problem and solved it?

**Comment by fwestenberg** [comment]
The site you mention is the HA documentation page. And since this is a HACS addon, it's not there. Just install HACS first, and let me know if this helps.

**Comment by EdmarS** [comment]
Hi, I had the same problem, at first. I copied reolink_dev into the custom_components and restarted HA.I upgraded from an older version of this add-on, so I had to remove the original camera platform setting reolink_dev from my configuration.yaml. Although I restarted HA several times, the Reolink IP Camera was not listed as an Integrations. Only after I restarted the ProxMox instance that is running HA, it finally showed up and after setting it up, it works great!

**Comment by wrpooley** [comment]
It’s working correctly now. I believe it was a browser issue because when
searching for the integration from a different device it showed up and was
able to install.

**Comment by j0rdyk** [comment]
Thanks, working nicely now with custom adding https://github.com/fwestenberg/reolink_dev to HACS :)

**Comment by Freestila** [comment]
So i have the same problem. Clearing the cache did not work. @j0rdyk , how did you do this custom adding? i could not find anything online for this.

**Comment by Freestila** [comment]
Had the same problem. Cache clearing did not work, or restart. Only as a custom repo url this worked.

**Comment by faquaresma** [comment]
Hi,

I instaled the integration by Custom repository on Hacs, but i haven't  any fields to fill with camera information,

Where i can find that information ?

Thanks in advance

**Comment by fwestenberg** [comment]
Did you check the readme?

**Comment by KptnKMan** [comment]
Something important to mention for @fwestenberg

If this is is a HACS addon, then the details in this repo are misleading, or at the very least missing steps.

Installation instructions in the README.md should not indicate to install using the normal "Configuration->Integrations" page:
![image](https://user-images.githubusercontent.com/12234043/104810300-d3fa5580-57f3-11eb-937f-e425c38a3b8c.png)

It does not appear:
![image](https://user-images.githubusercontent.com/12234043/104810377-5f73e680-57f4-11eb-95f0-7a8fa4472562.png)

Also, is not accessible using the "Add-on Store":
![image](https://user-images.githubusercontent.com/12234043/104810354-42d7ae80-57f4-11eb-81ff-16f165f5c45e.png)

**This issue really should not have been closed without fixing and clarifying the installation details.**

The installation instructions should read: ""HACS->Integrations->Top-Right Menu->Custom Repositories->Enter Custom Repository URL->Category: "integration"->Click "ADD" button->RESTART HA**

![image](https://user-images.githubusercontent.com/12234043/104810848-bfb85780-57f7-11eb-8ee8-fef10061a19c.png)

**Comment by KptnKMan** [comment]
Something important to mention for @fwestenberg

If this is is a HACS addon, then the details in this repo are misleading, or at the very least missing steps.

Installation instructions in the README.md should not indicate to install using the normal "Configuration->Integrations" page:
![image](https://user-images.githubusercontent.com/12234043/104810300-d3fa5580-57f3-11eb-937f-e425c38a3b8c.png)

It does not appear:
![image](https://user-images.githubusercontent.com/12234043/104810377-5f73e680-57f4-11eb-95f0-7a8fa4472562.png)

Also, is not accessible using the "Add-on Store":
![image](https://user-images.githubusercontent.com/12234043/104810354-42d7ae80-57f4-11eb-81ff-16f165f5c45e.png)

The installation instructions should read: ""HACS->Integrations->Top-Right Menu->Custom Repositories->Enter Custom Repository URL->Category: "integration"->Click "ADD" button->RESTART HA**

![image](https://user-images.githubusercontent.com/12234043/104810848-bfb85780-57f7-11eb-8ee8-fef10061a19c.png)

**This issue really should not have been closed without fixing and clarifying the installation details.**

**Comment by KptnKMan** [comment]
Something important to mention for @fwestenberg

If this is is a HACS addon, then the details in this repo are misleading, or at the very least missing steps.

Installation instructions in the README.md should not indicate to install using the normal "Configuration->Integrations" page:
![image](https://user-images.githubusercontent.com/12234043/104810300-d3fa5580-57f3-11eb-937f-e425c38a3b8c.png)

It does not appear:
![image](https://user-images.githubusercontent.com/12234043/104810377-5f73e680-57f4-11eb-95f0-7a8fa4472562.png)

Also, is not accessible using the "Add-on Store":
![image](https://user-images.githubusercontent.com/12234043/104810354-42d7ae80-57f4-11eb-81ff-16f165f5c45e.png)

The installation instructions should read: **"HACS->Integrations->Top-Right Menu->Custom Repositories->Enter Custom Repository URL->Category: "integration"->Click "ADD" button->RESTART HA**

![image](https://user-images.githubusercontent.com/12234043/104810848-bfb85780-57f7-11eb-8ee8-fef10061a19c.png)

**This issue really should not have been closed without fixing and clarifying the installation details.**

**Comment by badabing2005** [comment]
@KptnKMan 
It is a two part process
1- You add the component through HACS or manually.
2- You configure the integration through "Configuration->Integrations" page, just like the instructions state.

**Comment by KptnKMan** [comment]
> @KptnKMan 
> It is a two part process
> 1- You add the component through HACS or manually.
> 2- You configure the integration through "Configuration->Integrations" page, just like the instructions state.
> 
> Part 1 has always been the case
> Part 2 used to be through YAML configuration files, now (I think since version 0.7 or 0.8) it's integrated and can be done through HASS UI.

And your point is what?

The installation docs need to be updated.

This issue should bit have been closed without the docs being updated.

**Comment by badabing2005** [comment]
> 
> 
> > @KptnKMan
> > It is a two part process
> > 1- You add the component through HACS or manually.
> > 2- You configure the integration through "Configuration->Integrations" page, just like the instructions state.
> > Part 1 has always been the case
> > Part 2 used to be through YAML configuration files, now (I think since version 0.7 or 0.8) it's integrated and can be done through HASS UI.
> 
> And your point is what?
> 
> The installation docs need to be updated.
> 
> This issue should NOT have been closed without the docs being updated.

Do you really don't get the point? Or are you trying to provoke?
If it is the former, I'll oblige and spell it out for you, if it is the latter, I don't want any part of it.

**Comment by KptnKMan** [comment]
> > 
> > 
> > > @KptnKMan
> > > It is a two part process
> > > 1- You add the component through HACS or manually.
> > > 2- You configure the integration through "Configuration->Integrations" page, just like the instructions state.
> > > Part 1 has always been the case
> > > Part 2 used to be through YAML configuration files, now (I think since version 0.7 or 0.8) it's integrated and can be done through HASS UI.
> > 
> > And your point is what?
> > 
> > The installation docs need to be updated.
> > 
> > This issue should NOT have been closed without the docs being updated.
> 
> Do you really don't get the point? Or are you trying to provoke?
> If it is the former, I'll oblige and spell it out for you, if it is the latter, I don't want any part of it.
> 

I think you don't get the point.

If it is a two part process, as you have stated, PUT IT IN THE DOCS.

How hard is that to understand?

**Comment by fwestenberg** [comment]
@KptnKMan This integration is just shared with you to use, I don't own you anything. Also I close whatever issue I want to close. I expect people to know how HACS works, or how to use custom components. If not, just Google because this is already documented. At last: did you even consider to contribute? Send me a PR (this means Pull Request), like some other users did. Thanks!

**Comment by KptnKMan** [comment]
@fwestenberg Actually I considered putting together a PR for this, and honestly clearly I have Googled and done my research, finding THIS CLOSED ISSUE, with the other people who indicated their confusion. Clearly I've also provided a clear reasoning for what I'm talking about also.

I understand this is your project, but reading through this issue and others, it's clear that the installation documentation you provided is insufficient. I've also indicated here what it should read.

If you want people to use your project, basic and relevant documentation is important. What else do you expect? 

I'm not even making an unreasonable point.
Your documentation is incorrect, is misleading people, and this issues existence is proof of that. You can either take this as constructive criticism, or be defensive (“I can close whatever issue I want to close“).

Good luck.
