### ISSUE TITLE
Motion Detection not workin on NVR

### ISSUE THREAD

**Issue by d4yz** [fwestenberg/reolink_dev#124]
Hello, I use this tool with a NVR. All function seems to work except motion detection. The motion detect is always 'Clear' on all channels in home assistant. I am unsure if motion can be detected from the NVR. I found the below api call with the response.

API Call: http://192.168.1.60/api.cgi?cmd=GetMdState&user=admin&password=123&channel=0

Response:

[
 {
  cmd: "GetMdState",
  code: 1,
  error: {
   detail: "check err",
   rspCode: -3
  }
 }
]

The NVR is RLN8-410 with 4 D500 cameras.

**Comment by fwestenberg** [comment]
Thanks, there is already a issue for this. I renamed it to make this clear: https://github.com/fwestenberg/reolink_dev/issues/100
