### ISSUE TITLE
0.11 - duplicate entities after upgrade

### ISSUE THREAD

**Issue by andriej** [fwestenberg/reolink_dev#128]
**Describe the bug**
After update in HACS and restart of HA - all of camera entities were recreated with _2 in name and thus duplicated within same device

**To Reproduce**
Upgrade to v 0.11 and restart

**Expected behavior**
Keep entities

**Screenshots**
![image](https://user-images.githubusercontent.com/6303489/104590674-f3667680-566b-11eb-91db-3b60d4a6308c.png)

**Environment:**
Please provide useful information about your environment, like:
 - Home Assistant version - latest 2021.1.1
 - Reolink camera model RLC-520
 - Camera firmware number v3.0.0.136_20121112

**Additional context**
n/a

**Comment by fwestenberg** [comment]
I had the same. Apparently the device registry got changed so the old entities should be deleted or first delete the configured camera. Check R12 please.

**Comment by fwestenberg** [comment]
I missed a PR, so add this also to v0.12. Sorry for the inconvenience.

**Comment by andriej** [comment]
Same thing happened after upgrade to 0.12 and restart (I've deleted and re-added cameras in 0.11 if it's anything important)

**Comment by fwestenberg** [comment]
Yes, that is why the again need te be added. I expect it't not needed after this time.

**Comment by andriej** [comment]
Ok, re-added again in 0.12, will check with future version ;-)
