### ISSUE TITLE
HA integrations missing?

### ISSUE THREAD

**Issue by nic0dk** [fwestenberg/reolink_dev#131]
Hi, really nice integration 
after adding the custom repo under HACS, and installing Reolink custom components via HACS + reboot HA, im unable to find any Reolink integration under HA integration, am i the only one having this problem?
![image](https://user-images.githubusercontent.com/14346463/104823942-3b44f380-584e-11eb-98b0-066c06b7e582.png)
![image](https://user-images.githubusercontent.com/14346463/104823951-51eb4a80-584e-11eb-8002-6a254b791522.png)

is there anything i can do to troubleshoot this, im not seeing any logs about it failing.

**Comment by fwestenberg** [comment]
Some reported clearing browser cache helps. Did you try this?

**Comment by nic0dk** [comment]
@fwestenberg that did it!  thanks!

**Comment by fwestenberg** [comment]
Nice! Thanks for reporting!
