### ISSUE TITLE
hassio 2021.1.4 - The reolink_dev platform for the camera integration does not support platform setup. Please remove it from your config.

### ISSUE THREAD

**Issue by aisbergde** [fwestenberg/reolink_dev#132]
**Describe the bug**
reolink_dev worked fine until a few hours ago.

Then I updated to the latest version:
- HACS
- reolink_dev
 
I restarted HASSIO, but unfortunately I did not check if the cameras still work or not.

Then I updatet HASSIO from 2021.1.1 to 2021.1.4

And only then I checked the cameras. reolink cameras stopped to work. I get these kind of errors in the `home-assitent.log`

>2021-01-17 10:08:11 ERROR (MainThread) [homeassistant.components.camera] The reolink_dev platform for the camera integration does not support platform setup. Please remove it from your config.
>2021-01-17 10:08:11 ERROR (MainThread) [homeassistant.components.camera] The reolink_dev platform for the camera integration does not support platform setup. Please remove it from your config.

**To Reproduce**
use the latest version of hassio, hacs, reolink_dev

here is an example of my configuration, nothing special:

>- platform: reolink_dev
>  host: 192.168.178.2xx
>  username: yyyyy
>  password: !secret camera_reolink_password
>  name: Garage

**Expected behavior**
I want to be able to use the cameras again

**Screenshots**

**Environment:**
Please provide useful information about your environment, like:
 - Home Assistant version  
   2021.1.4
 - Reolink camera model
   any reolink camera
 - Camera firmware number

**Additional context**

**Comment by fwestenberg** [comment]
That's right. From now, you can just set it up from the integrations menu. Please see the readme.

**Comment by aisbergde** [comment]
it looks like it was this small comment in the release?

> If you are migrating from <0.7, please remove all existing config and use the config flow to add your camera(s).

It was not clear for me that this was a breaking change.
I would suggest marking this in the release history as "breaking change"

**Comment by fwestenberg** [comment]
You're right! I'll try to change this comment.
