### ISSUE TITLE
Question: How to change userid / password of registered camera

### ISSUE THREAD

**Issue by ed-holland** [fwestenberg/reolink_dev#133]
I've received this message from a registered camera:
`User guest has authorisation level guest. Only admin users can change camera settings! Switches will not work.`

There is no option to change the uid/pwd. Can it only be changed by deleting an re-registering?

**Comment by fwestenberg** [comment]
Hi Ed, that's right. Just re-add the integration with an admin user.

**Comment by ed-holland** [comment]
Thx for the quick answer.
