### ISSUE TITLE
Reolink RLC-410W unable to connect to Home Assistant 2021.1.4

### ISSUE THREAD

**Issue by ironhome** [fwestenberg/reolink_dev#135]
Hi,

i have Reolink C1 Pro that connected via eth using your integration without issue
today i get my new Reolink RLC-410W, set static IP eth and wifi

trying to connect via eth or wifi and get "Failed to connect with the camera"

No problem connect the camera via mobile app.

any suggestion ?

tnx

**Comment by fwestenberg** [comment]
Hi @ironhome,

Are you saying the C1 Pro is fully working: switches, motion detection and streaming?
I really don't have a clue, please provide logging, details about your installation etc as the template suggest!

**Comment by fwestenberg** [comment]
No info provided. Please fill in the form.
