### ISSUE TITLE
E1Pro support

### ISSUE THREAD

**Issue by SinnoTech** [fwestenberg/reolink_dev#137]
This isnt a bug, it so far works well with my RLC-410W, but I would have loved to be able to add the E1Pro. I saw in the documentation that it is unsupported. 

Will this be supported in the future? Or is there a technical reason it cannot be supported?

**Comment by fwestenberg** [comment]
I don't own an E1 kind of camera. If you send me your email I can provide a SoapUI package to test the features of the camera's. And maybe we can support it. The documentation is based on the findings of other users.

**Comment by SinnoTech** [comment]
Thanks. Sinnohometech@gmail.com

**Comment by MrHollowPS** [comment]
@SinnoTech @fwestenberg From what i saw reolink_dev uses the HTTP interface to connect to the cameras, and unfortunately the E1 Pro does not support HTTP. I've asked Reolink to provide HTTP support for it but this was the response i got:

```
Thank you for choosing Reolink.

One of the differences between E1 ZOOM and E1 PRO is whether it supports HTTP protocol. 

So unfortunately E1 PRO cannot support HTTP protocol now. This is related to the camera chip, the chip lacks this function.

If you need to use the HTTP protocol, I suggest you buy the E1 ZOOM camera, we are very willing to provide you with a good discount!

Thanks for your patience.
```

I fixed this issue by selling the E1 Pro and getting the E1 Zoom instead :)

**Comment by fwestenberg** [comment]
I think @MrHollowPS provided enough info about this issue. I will close it for this reason, also the camera is on the not-supported list in the readme. Can someone please clarify if the E1 Zoom is fully working?

**Comment by GeertvanHorrik** [comment]
I am having a similar issue. It took me a while to link the camera to QVR pro (QNAP NAS) as well, but it seems you need to use port 8000. It does not support HTTP but maybe this component can fallback on something else?

**Comment by GeertvanHorrik** [comment]
Some more info:

https://support.reolink.com/hc/en-us/articles/360007010473-How-to-Live-View-Reolink-Cameras-via-VLC-Media-Player

The url that is working for me is:

rtsp://[USERNAME]:[PWD]@[IP]:554//h264Preview_01_main

**Comment by MrHollowPS** [comment]
@fwestenberg yes the E1 Zoom is working perfectly, i have 3 cameras setup.

**Comment by labaland** [comment]
i have E1 Pro too :(

**Comment by GeertvanHorrik** [comment]
> i have E1 Pro too :(

As a workaround I "just" added the camera as ONVIF camera.

**Comment by labaland** [comment]
> > i have E1 Pro too :(
> 
> As a workaround I "just" added the camera as ONVIF camera.

Yeah i have that too atm, but i get some seconds delay 5-10 seconds. You too ?

**Comment by GeertvanHorrik** [comment]
I think that's always the case with a streaming cam, it needs to record, encode, then send over the network.

About the audio:

1. Make sure record audio is enabled via the reolink app
2. Make sure that when using the cards in lovelace, you actually define the camera as well:

```
- type: picture-entity
  title: Attic
  show_header_toggle: false
  entity: camera.attic
  camera_image: camera.attic <===== will show steam *without* audio if you don't include this one
  camera_view: live
```

**Comment by labaland** [comment]
> I think that's always the case with a streaming cam, it needs to record, encode, then send over the network.
> 
> About the audio:
> 
> 1. Make sure record audio is enabled via the reolink app
> 2. Make sure that when using the cards in lovelace, you actually define the camera as well:
> 
> ```
> - type: picture-entity
>   title: Attic
>   show_header_toggle: false
>   entity: camera.attic
>   camera_image: camera.attic <===== will show steam *without* audio if you don't include this one
>   camera_view: live
> ```

Thanks for the tip but it did not work for me :/
