### ISSUE TITLE
Motion Sensor - Error Renewing Subscription

### ISSUE THREAD

**Issue by danbayliss** [fwestenberg/reolink_dev#150]
**Describe the bug**
I'm not sure if this is related to other bugs reported on here but the motion sensor for my camera keeps going into unavailable and I have to reboot HA for it to come back. The camera feed itself continues to work and all other camera motion sensors work fine

**To Reproduce**
I can't reproduce it but it seems to happen ever day

**Screenshots**
![Screenshot_3](https://user-images.githubusercontent.com/54558493/106928707-5dbe8400-670b-11eb-81a9-73b02c8d7dc1.jpg)
![Screenshot_2](https://user-images.githubusercontent.com/54558493/106928717-6020de00-670b-11eb-9f22-7cec51ada792.jpg)

**Comment by acateon** [comment]
I got the same problem. In my case it might also drop the video feed as well.

**Comment by mezzagianni** [comment]
Same problem here.

**Comment by badabing2005** [comment]
Yes, this is the same issue discussed in the other threads,
After a while the NVR goes into a wonky state, and it's the NVR that needs to be restarted and not HASS
I have set my NVR to reboot daily (under maintenance menu), and for now this works, of course due to NVR software limitations (which Reolink is currently working on addressing) only motions from the first camera are actually triggered via onvif.

**Comment by danbayliss** [comment]
I don't have an NVR so not sure if it is the same

**Comment by acateon** [comment]
I’m not using a NVR either...

**Comment by badabing2005** [comment]
The root issue could be the same, but let's not make any assumptions, let's keep it open.
Does it start working if you restart the camera? (Not HASS)

**Comment by danbayliss** [comment]
Restarting the camera does not resolve the issue

**Comment by markxroberts** [comment]
I have the same issue.  NVR with latest firmware. 12 cameras.  Motion sensors always unavailable. Reboots of either CCTV or Hass don’t work.  All other device entities available.

**Comment by MiSSHeaDShoT** [comment]
Hello,
I can confirm same bug appears on E1 Zoom. After some time the motion sensor becomes unavailable. I managed to get it working by reloading the integration. Here is what the log says:

`2021-02-14 02:08:41 DEBUG (MainThread) [reolink.subscription_manager] Host 192.168.2.131 should renew in: 270 seconds...
2021-02-14 02:08:41 DEBUG (MainThread) [reolink.subscription_manager] Reolink host 192.168.2.131 got response status: 400. Payload: {<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://www.w3.org/2003/05/soap-envelope" xmlns:SOAP-ENC="http://www.w3.org/2003/05/soap-encoding" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsa="http://schemas.xmlsoap.org/ws/2004/08/addressing" xmlns:wsdd="http://schemas.xmlsoap.org/ws/2005/04/discovery" xmlns:wsa5="http://www.w3.org/2005/08/addressing" xmlns:xmime="http://tempuri.org/xmime.xsd" xmlns:xmime5="http://www.w3.org/2005/05/xmlmime" xmlns:xop="http://www.w3.org/2004/08/xop/include" xmlns:wsrfbf="http://docs.oasis-open.org/wsrf/bf-2" xmlns:tt="http://www.onvif.org/ver10/schema" xmlns:wstop="http://docs.oasis-open.org/wsn/t-1" xmlns:wsrfr="http://docs.oasis-open.org/wsrf/r-2" xmlns:ns1="http://www.onvif.org/ver10/actionengine/wsdl" xmlns:tev="http://www.onvif.org/ver10/events/wsdl" xmlns:ns10="http://www.onvif.org/ver10/events/wsdl/PullPointBinding" xmlns:ns11="http://www.onvif.org/ver10/events/wsdl/CreatePullPointBinding" xmlns:ns12="http://www.onvif.org/ver10/events/wsdl/PausableSubscriptionManagerBinding" xmlns:ns13="http://www.onvif.org/ver10/network/wsdl/RemoteDiscoveryBinding" xmlns:ns14="http://www.onvif.org/ver10/network/wsdl/DiscoveryLookupBinding" xmlns:tdn="http://www.onvif.org/ver10/network/wsdl" xmlns:ns3="http://www.onvif.org/ver20/analytics/wsdl/RuleEngineBinding" xmlns:ns4="http://www.onvif.org/ver20/analytics/wsdl/AnalyticsEngineBinding" xmlns:tan="http://www.onvif.org/ver20/analytics/wsdl" xmlns:ns5="http://www.onvif.org/ver10/events/wsdl/PullPointSubscriptionBinding" xmlns:ns6="http://www.onvif.org/ver10/events/wsdl/EventBinding" xmlns:ns7="http://www.onvif.org/ver10/events/wsdl/SubscriptionManagerBinding" xmlns:ns8="http://www.onvif.org/ver10/events/wsdl/NotificationProducerBinding" xmlns:wsnt="http://docs.oasis-open.org/wsn/b-2" xmlns:ns9="http://www.onvif.org/ver10/events/wsdl/NotificationConsumerBinding" xmlns:tad="http://www.onvif.org/ver10/analyticsdevice/wsdl" xmlns:tds="http://www.onvif.org/ver10/device/wsdl" xmlns:timg="http://www.onvif.org/ver20/imaging/wsdl" xmlns:tls="http://www.onvif.org/ver10/display/wsdl" xmlns:tmd="http://www.onvif.org/ver10/deviceIO/wsdl" xmlns:tptz="http://www.onvif.org/ver20/ptz/wsdl" xmlns:trc="http://www.onvif.org/ver10/recording/wsdl" xmlns:trp="http://www.onvif.org/ver10/replay/wsdl" xmlns:trt="http://www.onvif.org/ver10/media/wsdl" xmlns:trv="http://www.onvif.org/ver10/receiver/wsdl" xmlns:tse="http://www.onvif.org/ver10/search/wsdl" xmlns:ter="http://www.onvif.org/ver10/error" xmlns:tns1="http://www.onvif.org/ver10/topics" xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"><SOAP-ENV:Header><wsa5:To SOAP-ENV:mustUnderstand="1">http://192.168.246.251:8000/onvif/Notification?Idx=00_1</wsa5:To><wsa5:Action SOAP-ENV:mustUnderstand="1">http://docs.oasis-open.org/wsn/bw-2/SubscriptionManager/RenewRequest</wsa5:Action></SOAP-ENV:Header><SOAP-ENV:Body><SOAP-ENV:Fault><SOAP-ENV:Code><SOAP-ENV:Value>SOAP-ENV:Sender</SOAP-ENV:Value></SOAP-ENV:Code><SOAP-ENV:Reason><SOAP-ENV:Text xml:lang="en"/></SOAP-ENV:Reason></SOAP-ENV:Fault></SOAP-ENV:Body></SOAP-ENV:Envelope>
}
2021-02-14 02:08:41 DEBUG (MainThread) [reolink.subscription_manager] Reolink host 192.168.2.131 got response status: 200. Payload: {<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://www.w3.org/2003/05/soap-envelope" xmlns:SOAP-ENC="http://www.w3.org/2003/05/soap-encoding" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsa="http://schemas.xmlsoap.org/ws/2004/08/addressing" xmlns:wsdd="http://schemas.xmlsoap.org/ws/2005/04/discovery" xmlns:wsa5="http://www.w3.org/2005/08/addressing" xmlns:xmime="http://tempuri.org/xmime.xsd" xmlns:xmime5="http://www.w3.org/2005/05/xmlmime" xmlns:xop="http://www.w3.org/2004/08/xop/include" xmlns:wsrfbf="http://docs.oasis-open.org/wsrf/bf-2" xmlns:tt="http://www.onvif.org/ver10/schema" xmlns:wstop="http://docs.oasis-open.org/wsn/t-1" xmlns:wsrfr="http://docs.oasis-open.org/wsrf/r-2" xmlns:ns1="http://www.onvif.org/ver10/actionengine/wsdl" xmlns:tev="http://www.onvif.org/ver10/events/wsdl" xmlns:ns10="http://www.onvif.org/ver10/events/wsdl/PullPointBinding" xmlns:ns11="http://www.onvif.org/ver10/events/wsdl/CreatePullPointBinding" xmlns:ns12="http://www.onvif.org/ver10/events/wsdl/PausableSubscriptionManagerBinding" xmlns:ns13="http://www.onvif.org/ver10/network/wsdl/RemoteDiscoveryBinding" xmlns:ns14="http://www.onvif.org/ver10/network/wsdl/DiscoveryLookupBinding" xmlns:tdn="http://www.onvif.org/ver10/network/wsdl" xmlns:ns3="http://www.onvif.org/ver20/analytics/wsdl/RuleEngineBinding" xmlns:ns4="http://www.onvif.org/ver20/analytics/wsdl/AnalyticsEngineBinding" xmlns:tan="http://www.onvif.org/ver20/analytics/wsdl" xmlns:ns5="http://www.onvif.org/ver10/events/wsdl/PullPointSubscriptionBinding" xmlns:ns6="http://www.onvif.org/ver10/events/wsdl/EventBinding" xmlns:ns7="http://www.onvif.org/ver10/events/wsdl/SubscriptionManagerBinding" xmlns:ns8="http://www.onvif.org/ver10/events/wsdl/NotificationProducerBinding" xmlns:wsnt="http://docs.oasis-open.org/wsn/b-2" xmlns:ns9="http://www.onvif.org/ver10/events/wsdl/NotificationConsumerBinding" xmlns:tad="http://www.onvif.org/ver10/analyticsdevice/wsdl" xmlns:tds="http://www.onvif.org/ver10/device/wsdl" xmlns:timg="http://www.onvif.org/ver20/imaging/wsdl" xmlns:tls="http://www.onvif.org/ver10/display/wsdl" xmlns:tmd="http://www.onvif.org/ver10/deviceIO/wsdl" xmlns:tptz="http://www.onvif.org/ver20/ptz/wsdl" xmlns:trc="http://www.onvif.org/ver10/recording/wsdl" xmlns:trp="http://www.onvif.org/ver10/replay/wsdl" xmlns:trt="http://www.onvif.org/ver10/media/wsdl" xmlns:trv="http://www.onvif.org/ver10/receiver/wsdl" xmlns:tse="http://www.onvif.org/ver10/search/wsdl" xmlns:ter="http://www.onvif.org/ver10/error" xmlns:tns1="http://www.onvif.org/ver10/topics" xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"><SOAP-ENV:Header><wsa5:To SOAP-ENV:mustUnderstand="1">http://192.168.246.251:8000/onvif/Notification?Idx=00_1</wsa5:To><wsa5:Action SOAP-ENV:mustUnderstand="1">http://docs.oasis-open.org/wsn/bw-2/SubscriptionManager/UnsubscribeRequest</wsa5:Action></SOAP-ENV:Header><SOAP-ENV:Body><wsnt:UnsubscribeResponse></wsnt:UnsubscribeResponse></SOAP-ENV:Body></SOAP-ENV:Envelope>
}
2021-02-14 02:08:41 ERROR (MainThread) [custom_components.reolink_dev.base] Host 192.168.2.131 error renewing the Reolink subscription
2021-02-14 02:08:41 DEBUG (MainThread) [reolink.subscription_manager] Reolink host 192.168.2.131 got response status: 200. Payload: {<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://www.w3.org/2003/05/soap-envelope" xmlns:SOAP-ENC="http://www.w3.org/2003/05/soap-encoding" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsa="http://schemas.xmlsoap.org/ws/2004/08/addressing" xmlns:wsdd="http://schemas.xmlsoap.org/ws/2005/04/discovery" xmlns:wsa5="http://www.w3.org/2005/08/addressing" xmlns:xmime="http://tempuri.org/xmime.xsd" xmlns:xmime5="http://www.w3.org/2005/05/xmlmime" xmlns:xop="http://www.w3.org/2004/08/xop/include" xmlns:wsrfbf="http://docs.oasis-open.org/wsrf/bf-2" xmlns:tt="http://www.onvif.org/ver10/schema" xmlns:wstop="http://docs.oasis-open.org/wsn/t-1" xmlns:wsrfr="http://docs.oasis-open.org/wsrf/r-2" xmlns:ns1="http://www.onvif.org/ver10/actionengine/wsdl" xmlns:tev="http://www.onvif.org/ver10/events/wsdl" xmlns:ns10="http://www.onvif.org/ver10/events/wsdl/PullPointBinding" xmlns:ns11="http://www.onvif.org/ver10/events/wsdl/CreatePullPointBinding" xmlns:ns12="http://www.onvif.org/ver10/events/wsdl/PausableSubscriptionManagerBinding" xmlns:ns13="http://www.onvif.org/ver10/network/wsdl/RemoteDiscoveryBinding" xmlns:ns14="http://www.onvif.org/ver10/network/wsdl/DiscoveryLookupBinding" xmlns:tdn="http://www.onvif.org/ver10/network/wsdl" xmlns:ns3="http://www.onvif.org/ver20/analytics/wsdl/RuleEngineBinding" xmlns:ns4="http://www.onvif.org/ver20/analytics/wsdl/AnalyticsEngineBinding" xmlns:tan="http://www.onvif.org/ver20/analytics/wsdl" xmlns:ns5="http://www.onvif.org/ver10/events/wsdl/PullPointSubscriptionBinding" xmlns:ns6="http://www.onvif.org/ver10/events/wsdl/EventBinding" xmlns:ns7="http://www.onvif.org/ver10/events/wsdl/SubscriptionManagerBinding" xmlns:ns8="http://www.onvif.org/ver10/events/wsdl/NotificationProducerBinding" xmlns:wsnt="http://docs.oasis-open.org/wsn/b-2" xmlns:ns9="http://www.onvif.org/ver10/events/wsdl/NotificationConsumerBinding" xmlns:tad="http://www.onvif.org/ver10/analyticsdevice/wsdl" xmlns:tds="http://www.onvif.org/ver10/device/wsdl" xmlns:timg="http://www.onvif.org/ver20/imaging/wsdl" xmlns:tls="http://www.onvif.org/ver10/display/wsdl" xmlns:tmd="http://www.onvif.org/ver10/deviceIO/wsdl" xmlns:tptz="http://www.onvif.org/ver20/ptz/wsdl" xmlns:trc="http://www.onvif.org/ver10/recording/wsdl" xmlns:trp="http://www.onvif.org/ver10/replay/wsdl" xmlns:trt="http://www.onvif.org/ver10/media/wsdl" xmlns:trv="http://www.onvif.org/ver10/receiver/wsdl" xmlns:tse="http://www.onvif.org/ver10/search/wsdl" xmlns:ter="http://www.onvif.org/ver10/error" xmlns:tns1="http://www.onvif.org/ver10/topics" xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"><SOAP-ENV:Header></SOAP-ENV:Header><SOAP-ENV:Body><wsnt:SubscribeResponse><wsnt:SubscriptionReference><wsa5:Address>http://192.168.160.126:8000/onvif/Notification?Idx=00_0</wsa5:Address></wsnt:SubscriptionReference><wsnt:CurrentTime>2021-02-14T00:08:47Z</wsnt:CurrentTime><wsnt:TerminationTime>2021-02-14T00:23:47Z</wsnt:TerminationTime></wsnt:SubscribeResponse></SOAP-ENV:Body></SOAP-ENV:Envelope>
}
2021-02-14 02:08:41 DEBUG (MainThread) [reolink.subscription_manager] Local time: 2021-02-14 00:08, camera time: 2021-02-14 00:08 (difference: 5.896687030792236), termination time: 2021-02-14 00:23
2021-02-14 02:08:41 DEBUG (MainThread) [custom_components.reolink_dev] Finished fetching reolink data in 0.240 seconds
2021-02-14 02:08:41 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event state_changed[L]: entity_id=binary_sensor.hallway_camera_motion, old_state=<state binary_sensor.hallway_camera_motion=off; friendly_name=Hallway camera motion, device_class=motion @ 2021-02-14T01:30:37.691018+02:00>, new_state=<state binary_sensor.hallway_camera_motion=unavailable; friendly_name=Hallway camera motion, device_class=motion @ 2021-02-14T02:08:41.241958+02:00>>`

**Comment by spf13** [comment]
Can confirm happening here too. NVR with latest firmware, only 1 camera (so far).

**Comment by danbayliss** [comment]
Hi. It looks like the latest update has resolved this. I've not experienced it in the last 24hrs

**Comment by p4mr** [comment]
I'm getting the same error (no obvious pattern though)

Setup is single RLC-410 camera, 64Gb micro SD card on board, with no NVR. Camera set to enable FTP, Email, IR and Record Audio &Video automatically on motion at 11pm every day (disable at 7am). Error is as follows.

` Logger: custom_components.reolink_dev.base
Source: custom_components/reolink_dev/base.py:267
Integration: Reolink IP camera (documentation, issues)
First occurred: 02:34:42 (1 occurrences)
Last logged: 02:34:42
Host 192.168.1.53 error renewing the Reolink subscription`

**Comment by richsimpson** [comment]
Yes same issue for me. noticed when I restored a snapshot that predated adding reolink. Added the integration again and now getting the error renewing Reolink subscription and the unregistered webhook, 1 per camera on the NVR
![image](https://user-images.githubusercontent.com/51749826/124890389-e77ec000-dfcf-11eb-8476-3f1fae85f31e.png)

**Comment by onkytonk** [comment]
Was this issue ever resolved? I'm now experiencing the same "error renewing the Reolink subscription" in my log. 
Camera feeds work, but will occasionally stop, but come back after rebooting the NVR. 
I have 8 cameras and currently only 2 motion sensors are working, the rest are "unavailable". 

NVR is RLN16-410
Cameras are mixed reolink POE cameras. 
HA v2021.7.0
reolink_dev v0.17

**Comment by markxroberts** [comment]
This issue wasn't resolved.  It seems to be a problem related to using the NVR and the sensor subscription protocol.  Individual cameras work, but when linked via the NVR they don't.

**Comment by richsimpson** [comment]
I gave up as unreliable for now, hoping a fix comes along as the first impression was it was much faster than having the direct feeds in HASS. That said, I tried everything I could think of, removing the integration and component and all the reboots, at one stage I set 8 x users on the NVR hass1, hass2, hass3 and it seemed to be good, the first few cameras went on and 5 mins later no errors, then suddenly they started coming through. I had all the sensors disabled but the simple feed, but no good. For now I am resorting to the feeds in the configuration.yaml directly and setting them that way. Hoping a better solution comes along when the dev has time to try to solve it. Greta work, just not for me at the moment.

**Comment by Fannangir** [comment]
Could you please explain how can I do it directly via yaml (share your config)?
Meaning, can you read the sensors via yaml or just the stream?

**Comment by richsimpson** [comment]
It is just the stream, but here is my config, I use an NVR so for me stream 1-8 is channel 0-8. So for the first one I have something like this:     input: rtmp://192.168.0.11/bcs/channel0_main.bcs?&user=USER&password=PASS 
That is Channel 0 = channel 1 on NVR, but if its a camera direct I think 0 is the only feed. main is main stream though ext is medium and sub is low.

Not sure formatting will copy over correctly so may need to be careful of that.

My entry in configuration.yaml on HASS.

#Cameras used to create devices, used in remote cctv feed, used in dash2. not used
#for the local cctv dashboard webrtc
camera:
  - platform: ffmpeg
    name: CCTV1 Front Door
    input: rtmp://192.168.0.11/bcs/channel0_main.bcs?&user=USER&password=PASS
  - platform: ffmpeg
    name: CCTV2 Front Drive
    input: rtmp://IP OF NVR/bcs/channel1_main.bcs?&user=USER&password=PASS
  - platform: ffmpeg
    name: CCTV3 Back Garden
    input: rtmp://IP OF NVR/bcs/channel2_main.bcs?&user=USER&password=PASS
  - platform: ffmpeg
    name: CCTV4 Rear House
    input: rtmp://IP OF NVR/bcs/channel3_main.bcs?&user=USER&password=PASS
  - platform: ffmpeg
    name: CCTV5 Garage
    input: rtmp://IP OF NVR/bcs/channel4_main.bcs?&user=USER&password=PASS
  - platform: ffmpeg
    name: CCTV6 Play Room
    input: rtmp://IP OF NVR/bcs/channel5_main.bcs?&user=USER&password=PASS
  - platform: ffmpeg
    name: CCTV7 Cinema Room
    input: rtmp://IP OF NVR/bcs/channel6_main.bcs?&user=USER&password=PASS
  - platform: ffmpeg
    name: CCTV8 Utility Room
    input: rtmp://IP OF NVR/bcs/channel7_main.bcs?&user=USER&password=PASS
  - platform: ffmpeg
    name: CCTV1 Front Door LQ
    input: rtmp://IP OF NVR/bcs/channel0_sub.bcs?&user=USER&password=PASS
  - platform: ffmpeg
    name: CCTV2 Front Drive LQ
    input: rtmp://IP OF NVR/bcs/channel1_sub.bcs?&user=USER&password=PASS
  - platform: ffmpeg
    name: CCTV3 Back Garden LQ
    input: rtmp://IP OF NVR/bcs/channel2_sub.bcs?&user=USER&password=PASS
  - platform: ffmpeg
    name: CCTV4 Rear House LQ
    input: rtmp://IP OF NVR/bcs/channel3_sub.bcs?&user=USER&password=PASS
  - platform: ffmpeg
    name: CCTV5 Garage LQ
    input: rtmp://IP OF NVR/bcs/channel4_sub.bcs?&user=USER&password=PASS
  - platform: ffmpeg
    name: CCTV6 Play Room LQ
    input: rtmp://IP OF NVR/bcs/channel5_sub.bcs?&user=USER&password=PASS
  - platform: ffmpeg
    name: CCTV7 Cinema Room LQ
    input: rtmp://IP OF NVR/bcs/channel6_sub.bcs?&user=USER&password=PASS
  - platform: ffmpeg
    name: CCTV8 Utility Room LQ
    input: rtmp://IP OF NVR/bcs/channel7_sub.bcs?&user=USER&password=PASS
#templates for video change channel from 0-7 for stream 1-8
# 1 lowQ 640x480 px input: rtmp://IP OF NVR/bcs/channel0_sub.bcs?&user=USER&password=PASS
# 2 medQ 896x672 px input: rtmp://IP OF NVR/bcs/channel0_ext.bcs?&user=USER&password=PASS
# 3 highQ 2560x1920 px input: rtmp://IP OF NVR/bcs/channel0_main.bcs?&user=USER&password=PASS

**Comment by richsimpson** [comment]
Not sure that worked, maybe this will!
<script src="https://pastebin.com/embed_js/EetWnK8t"></script>

**Comment by Fannangir** [comment]
Thank you very much.
Will try it out.
I guess there is no solution for the motion sensors.

**Comment by danbayliss** [comment]
This issue was fixed for me in a previous update so i'm closing this down. If you still have the issue please open a new issue
