### ISSUE TITLE
Allow to add a device more than once (depending on stream quality)

### ISSUE THREAD

**Issue by SaSa1983** [fwestenberg/reolink_dev#156]
It is currently not possible to add the same camera twice.
I want to use the "sub" profile for live preview in lovelace cards and the "main" profile when clicking the card.

Thus I'd need to add the same camera twice.

**Comment by fwestenberg** [comment]
I understand your idea. But this will generate a lot of issues: motion detection get registered twice, probably the camera will get to many logged in users or too many requests. Just use the generic camera component for this, with the URL like described [here](https://support.reolink.com/hc/en-us/articles/360007010473-How-to-Live-View-Reolink-Cameras-via-VLC-Media-Player).

**Comment by SaSa1983** [comment]
Okay, I'll use a "Generic Camera" to open the overlay.
Thanks a lot for your quick response.

Am Do., 18. Feb. 2021 um 10:43 Uhr schrieb fwestenberg <
notifications@github.com>:
