### ISSUE TITLE
Request for Service colour.turn_on / turn_off implementation

### ISSUE THREAD

**Issue by chiefcomm** [fwestenberg/reolink_dev#157]
With the later releases of firmware in Reolink cameras, Reolink introduced a Day and Night setting with 3 settings (Auto, color and Black & White) this Day/Night setting has an affect on the Infrared settings i.e. Day/Night = color which forces Infrared = off.

In the odd case that the camera resets and the Day/Night is reset to color the night time infrared is switched off negating the camera at night.  I have found my RLC-410-5MP resets to color when rebooted (once per week).

Therefore would it be possible to have this integration interact with the Day/Night setting to force the camera back to Auto during night hours.

Camera types:
RLC-410-5MP & RLC-420-5MP

**Comment by fwestenberg** [comment]
Read the documentation please. It's already there: service reolink_dev.set_daynight.
