### ISSUE TITLE
Reolink Integration not visible after installing in HACS on HA 2021.2.3

### ISSUE THREAD

**Issue by richardklingler** [fwestenberg/reolink_dev#158]
**Reolink integration 0.14 not visible in HA 2021.2.3**
After installing the Reolink camera HACS add-on and restarting/rebooting HA 2021.2.3 the Reolink integration is not visible under Configuration -> Integration

**To Reproduce**
- Add reolink repository
- Install add-on awith category Integration
- restart HA

**Expected behavior**
Going into Configuration -> Integration and select "Add integration" doesn't show the Reolink Camera Integration at all...
Nothing in the system logs.
Furthermore the Reolink add-on shows unformatted information in the HACS section:

![reolink_addon](https://user-images.githubusercontent.com/11256235/108844452-6f919980-75dc-11eb-91a3-3c1dfbcd3309.png)

**Comment by GrayForce** [comment]
It works for me (same Reolink integration 0.14 and HA 2021.2.3). I'm using rpi4 and HA OS.
May clearing the browser cache help?

>>Furthermore the Reolink add-on shows unformatted information in the HACS section:
I see this problem too.

**Comment by richardklingler** [comment]
It worked suddenly next day...did several restart of he device :-)
