### ISSUE TITLE
manifest.json Requires Version Tag

### ISSUE THREAD

**Issue by RobertD502** [fwestenberg/reolink_dev#159]
Since the release of the latest HA beta, HA is starting to require custom integrations to have a version tag in the manifest.json file. According to the beta release notes: "For now, this will create a warning on startup. But this will eventually be blocked from loading if it’s missing a version in the manifest". Details regarding the change can be found in this [pull request](https://github.com/home-assistant/core/pull/45919).

**Comment by xannor** [comment]
this is fixed in #166 and should be in the next release.

**Comment by fwestenberg** [comment]
Fixed in version 0.15.
