### ISSUE TITLE
Ability to Set Backlight (Dynamic Range, Backlight, Off)

### ISSUE THREAD

**Issue by sea3pea0** [fwestenberg/reolink_dev#160]
I noticed that setting the backlight to Dynamic Range helps the image on my cameras quite a bit at night. But during the day having the backlight on causes the camera image to be washed out. It would be great to be able to control these settings with this addon so these settings could be handled by automations in HA. I have some RLC-410s and a couple RLC-810a's and the situation is the same on both cameras but more pronounced on the 810a. Thanks for the great addon!

**Comment by fwestenberg** [comment]
Added in version 0.15!

**Comment by fwestenberg** [comment]
So there is a service now, set_backlight. And also backlight_state is present as attribute on the camera entity.
