### ISSUE TITLE
Camera snapshot service from chosen stream source (sub/main)

### ISSUE THREAD

**Issue by acateon** [fwestenberg/reolink_dev#161]
**Describe the bug**
When the sub stream is selected for a camera, the HA snapshot service grabs a frame from the main profile.
Also the entity image is from the main stream.

**Additional context**
Snapshot from the sub stream when chosen as source in the setup would be great for external object processing speed.

**Comment by RestOp** [comment]
Hello,

i have the issure that i set up SUB stream in integration setting, but nothing changes, it works from MAIN stream also afetr restart of HA
![image](https://user-images.githubusercontent.com/46259141/111075558-deca2180-84e8-11eb-8ff4-97cea281f84d.png)

**Comment by fwestenberg** [comment]
For as far as I know, the snapshot has no option to choose quality. Check [here](https://support.reolink.com/hc/en-us/articles/360007011233-How-to-Capture-Live-JPEG-Image-of-Reolink-Cameras-via-Web-Browsers), there is no parameter included. The integration use the snapshot option from the CGI api, which has only those params:
'''
        param = {"cmd": "Snap", "channel": self._channel}
'''

Can you choose snapshot quality anywhere else, like the WebUI or Reolink Windows application?

**Comment by fwestenberg** [comment]
Also the command `/cgi-bin/api.cgi?cmd=onvifSnapPic&channel=0` has no quality option.
I'm closing this issue, please inform me if you find out how to do this.
