### ISSUE TITLE
Vehicle and Person motion detection

### ISSUE THREAD

**Issue by bigfeetneedbigboots** [fwestenberg/reolink_dev#163]
This is an enhancement request to include person motion and vehicle motion sensors in Home Assistant. I have an RLC-820A (firmware v3.0.0.177_21012101) which includes person and vehicle motion detection on-board the camera. It works very well in my environment and seems to mostly, if not completely, eliminate false motion triggers like birds or branches moving. I currently have the camera emailing me when it detects person or vehicle motion however it would be fabulous to have these as sensors in HA. A use case would be that if a vehicle is detected, the image is sent for number plate recognition. If a person is detected it could play an announcement in the house to let us know. 

Please let me know if more information required to support this feature request.

**Comment by fwestenberg** [comment]
Already existing request: #86
