### ISSUE TITLE
 No 'version' key in the manifest file for custom integration 'reolink_dev'.

### ISSUE THREAD

**Issue by elyobelyob** [fwestenberg/reolink_dev#167]
Couldn't see this mentioned anywhere in the issues ... "This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'reolink_dev'"

Thanks

**Comment by xannor** [comment]
this was fixed in #166 and should be in the next release.

**Comment by elyobelyob** [comment]
Thanks, sorry, I missed it. Was searching for the error message!
