### ISSUE TITLE
Can't Play Videos on Android Tablet

### ISSUE THREAD

**Issue by mathmaniac43** [fwestenberg/reolink_dev#168]
**Describe the bug**
Video not displaying in Home Assistant Companion app or Chrome app on my Samsung Galaxy A7 Android 10 tablet.

**To Reproduce**
1) Navigate to Home Assistant Lovelace dashboard with live video from Reolink camera (via Picture Entity). It is either totally black (Chrome), or has a gray square with a gray play button (Home Assistant Companion).
2) Click on the video and attempt to play in full screen. It is either black or gray as before. It appears to buffer something, but it is not visible or playable.

**Expected behavior**
The video should display and play, as it does in the Firefox browser on my tablet, or on Chrome or Firefox on my Windows computer.

**Screenshots**

**Environment:**
Please provide useful information about your environment, like:
 - Home Assistant version **2021.3.2**
 - Reolink camera model **RLC-410-5MP**
 - Camera firmware number **v3.0.0.136_20121100**

**Additional context**
- [related issue in `home-assistant/android`](https://github.com/home-assistant/android/issues/1355)
- [related issue in `home-assistant/frontend`](https://github.com/home-assistant/frontend/issues/8575)
- [related issue in `chromium`](https://bugs.chromium.org/p/chromium/issues/detail?id=1185597)

**Comment by fwestenberg** [comment]
Is this related to the Reolink component of is the tablet too old or something?

**Comment by mathmaniac43** [comment]
Honestly I was not sure where to start or what the root of the issue was, so I have ended up checking at all of the aforementioned repositories looking for help. My gut says it may be a Chromium thing (some kind of encoding issue maybe?), but I wanted to put this here in case someone else using the same cameras has the same trouble and can help shed additional light on the issue.

The tablet is literally brand-new (2020 model I think) and on Android 10.

**Comment by t0bse** [comment]
> Honestly I was not sure where to start or what the root of the issue was, so I have ended up checking at all of the aforementioned repositories looking for help. My gut says it may be a Chromium thing (some kind of encoding issue maybe?), but I wanted to put this here in case someone else using the same cameras has the same trouble and can help shed additional light on the issue. The tablet is literally brand-new (2020 model I think) and on Android 10.
> […](#)
> On Mar 8, 2021, at 04:32, fwestenberg ***@***.***> wrote: ﻿ Is this related to the Reolink component of is the tablet too old or something? — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

try setting your videostream to "sub" in reolink options - working?

**Comment by mathmaniac43** [comment]
@t0bse Per your recommendation, I changed the setting of one of my Reolink cameras via the HA Integrations menu to "sub". Still the same issue: it does not work on the tablet, but works fine on my phone and laptop.

**Comment by SaSa1983** [comment]
It might be possible that this a device specific problem.
Can you tell the manufacturer and model of your tablet?

Could you also try to set a camera up via "generic camera" integration?

I guess that your tablet has an issue with the video codec.

**Comment by mathmaniac43** [comment]
As I said in the submission, it is a Samsung Galaxy A7 Android 10 tablet.

The generic camera integration is a good idea, I will take a look at that.

I am having some luck with the Chromium developers (see link at bottom of submission), they also think it is likely a codec issue.

**Comment by justinmaiuto** [comment]
Hi was this ever solved? I have the exact same issue on a samsung a8
