### ISSUE TITLE
PTZ_CONTROL

### ISSUE THREAD

**Issue by ArcoSax** [fwestenberg/reolink_dev#172]
I am using this integration in HOME ASSISTANT for 2 RLC-410W model cameras.
Entities for the 2 devices have been successfully created.
I wanted to insert zoom buttons in lovelace but from the developer test menu I can't get the cameras to accept them.
These are the test lines for the service

service: reolink_dev.ptz_control
data:
  entity_id: camera.garden
  command: ZOOMDEC
  speed: 25

Surely I am wrong in something but at the moment I have only the doubt that the RLC-410W model does not exhibit the service. Unless some different settings to be made with its proprietary APP.

Thank you for your suggestions and I hope this report will improve the software

**Comment by fwestenberg** [comment]
I'm very sure the RLC-410W has no PTZ controls and/or zoom.

More [here](https://reolink.com/product/rlc-410w/#compare).
