### ISSUE TITLE
Integration, no device or entity

### ISSUE THREAD

**Issue by JoeNobod** [fwestenberg/reolink_dev#182]
Adding cameras under integration in HA does not create any devices or entities for the cameras.

Following to instructions I go to add integration, select Reolink IP camera, enter ip, username and password.  Camera is detected, but there is no selection screen afterwords showing the camera or the location.  The next screen only shows success.  (screenshots attached)

 - Home Assistant version - 2021.3.4
 - Reolink camera model - RLC-810A
 - Camera firmware number - v3.0.0.177_21012103

**Screenshots**
![Integration](https://user-images.githubusercontent.com/81011369/113258418-d3863c80-92c3-11eb-8940-6fd2d90fa828.png)
![Integration1](https://user-images.githubusercontent.com/81011369/113258420-d41ed300-92c3-11eb-8333-4f67fe774ff1.png)
![Integration3](https://user-images.githubusercontent.com/81011369/113258421-d41ed300-92c3-11eb-864b-e57bf6c5bd5e.png)
![Integration4](https://user-images.githubusercontent.com/81011369/113258423-d4b76980-92c3-11eb-9dab-4d4611ba2614.png)

**Comment by Medic97** [comment]
I have the same issue with C1 and E1 Zoom cameras on a brand new install of HA.

**Comment by marler** [comment]
same issue for my RLC-410W

**Comment by JoeNobod** [comment]
At least I know it's not just me having this issue and we can get it resolved.

**Comment by Ssereno** [comment]
Same problem. After install the addon i cant see the camera entity on integrations

**Comment by dewit-maeyaert-smarthome** [comment]
Same here. Worked before, but moved the camera to another installation and now it's gone.

**Comment by dewit-maeyaert-smarthome** [comment]
> Same here. Worked before, but moved the camera to another installation and now it's gone.

Fixed it! Make sure you set the internal/external URL under general. Think that fixed it.

**Comment by SergioWarriorPeru** [comment]
> > Same here. Worked before, but moved the camera to another installation and now it's gone.
> 
> Fixed it! Make sure you set the internal/external URL under general. Think that fixed it.

Hi, where must i do that?

**Comment by SergioWarriorPeru** [comment]
> > Same here. Worked before, but moved the camera to another installation and now it's gone.
> 
> Fixed it! Make sure you set the internal/external URL under general. Think that fixed it.

What do you have to set there? In my configuration it says External URL and Internal URL

**Comment by SergioWarriorPeru** [comment]
> > Same here. Worked before, but moved the camera to another installation and now it's gone.
> 
> Fixed it! Make sure you set the internal/external URL under general. Think that fixed it.

Yes, It works...although delay is almost 10 to 15 seconds

**Comment by JoeNobod** [comment]
> 
> 
> > Same here. Worked before, but moved the camera to another installation and now it's gone.
> 
> Fixed it! Make sure you set the internal/external URL under general. Think that fixed it.

Great, thanks.  Never thought that setting would affect the link.  Appreciate your fix!

**Comment by JoeNobod** [comment]
As this seems to have fixed the issue for me I will close this.  Thanks
