### ISSUE TITLE
Can't download assets (zip file)

### ISSUE THREAD

**Issue by bdollerup** [fwestenberg/reolink_dev#187]
When following the manual install instruction, I get an error that the file cannot be found.

Here's the part that fails:

# Download a copy of this repository
$ wget https://github.com/fwestenberg/reolink/archive/master.zip

I get an error when I try the following:
 wget https://github.com/fwestenberg/reolink/archive/master.zip

Here the error I get:
```
Resolving github.com (github.com)... 140.82.121.3
Connecting to github.com (github.com)|140.82.121.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/fwestenberg/reolink/zip/master [following]
--2021-05-10 16:22:47--  https://codeload.github.com/fwestenberg/reolink/zip/master
Resolving codeload.github.com (codeload.github.com)... 140.82.121.9
Connecting to codeload.github.com (codeload.github.com)|140.82.121.9|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-05-10 16:22:47 ERROR 404: Not Found.
````  

Can you point me to that correct download?

Thanks!

**Comment by fwestenberg** [comment]
It should be: https://github.com/fwestenberg/reolink_dev/archive/master.zip
