### ISSUE TITLE
AI Motion detection

### ISSUE THREAD

**Issue by skalman77** [fwestenberg/reolink_dev#191]
I'm using Reolink RLC-820A with AI motion detection. It would be great if the binary sensor could extract what is triggering the motion (Person or car), so i can create automations based on the motion status. Would it be possible to add this functionality?

**Comment by ralphvdwal** [comment]
I would like the same new sensors as possible

**Comment by Fannangir** [comment]
My RLC-810A and and RLC-820A are connected via NVR RLN16-410.
The sensors show unavailable.
NVR version is the latest, it shows the different notifications for car, person, etc.
Should the sensors work via NVR?
Thanks.

**Comment by fwestenberg** [comment]
There has always been a NVR issue, Reolink promised to fix this in some update. I only tested this with the 820A without NVR.

**Comment by skalman77** [comment]
Unfortunatly i cant make it work. I have installed latest firmware (build 21012101) and updated to latest version of the integration from hacs, and still only see motion detected as result. I expected to see what was causing the detection (person or car)

**Comment by cpainchaud** [comment]
It's actually showing here:
![image](https://user-images.githubusercontent.com/6696638/128678832-2959a577-7db3-4fe4-885c-d6f15077ec5e.png)
 yet @fwestenberg, what we could be missing is a binary_switch for all types of detection : an attribute is not easy to show in a Dashboard
