### ISSUE TITLE
E1 Pro not supported? 

### ISSUE THREAD

**Issue by dennidoubles** [fwestenberg/reolink_dev#192]
Don't know where to ask, so I try this way:

Is there a reason the E1 Pro isn't supported? Will it be supported in the future maybe?

I want to add some Reolinks, and wanted to buy E1 Pro's. 
But now I need to buy E1 Pro Zoom instead, if I want to integrate them in Home Assistant? 

Besides this, I'm very happy with the integration, my 510A camera's are integrated very well! Thanks for that

**Comment by fwestenberg** [comment]
Thanks! Just check out the closed issues, some are about the E1. There is no API available it seems.
