### ISSUE TITLE
Question about usage/recording

### ISSUE THREAD

**Issue by ovizii** [fwestenberg/reolink_dev#206]
Hi there,

I have successfully added my E1 zoom using your integration and was wondering if there is a way to manually trigger a recording? 

I don't use any detection via the camera so I was simply wondering how to manually trigger a recording or maybe via some workaround?

**Comment by chiefcomm** [comment]
I guess there are many ways to do this.   Myself I prefer to let the camera record to the internal memory card using the camera inbuilt logic (movement detection).  In addition I take photos (no video) when the alarm is set and movement is detected by sensor in that room (via automation).  In my case the cameras are turned to the wall when people are home and the alarm is not set.

There are a number of services you can choose from and with automation's build exactly what you want to do.

![image](https://user-images.githubusercontent.com/45157523/123719401-c974d980-d8c4-11eb-839e-9972f48d1270.png)

**Comment by ovizii** [comment]
hm, can you give me a few more pointers?

Like I said I would like to manually trigger recording, ideally writing to the camera's default storage space aka SD card.

The use case is that I have set up a camera as a sort of dog monitor to check up on what my dog is doing when I'm not home and sometimes she is so funny I just want to press record. 

Camera: Record looks like what I need but it looks like you can only record to HA storage, right? I gave it a test via HA => Developer Tools => Services

**Comment by chiefcomm** [comment]
@ovizii um sorry no as I just tried it myself and yes you are correct it seems to only be able to record to HA storage.   Maybe some other smart person following can suggest something.

I used the following command which recorded a lovely 15sec recording of an empty room :-)

    service: camera.record
    target:
      entity_id: camera.reolink_lounge
    data:
      filename: '/config/www/camera_roll/camera_reolink_lounge_{{ now().strftime("%Y%m%d-%H%M%S") }}.mp4'
      duration: 15

**Comment by ovizii** [comment]
seems reolink cameras have some minimal kind of API but it does not look like one could trigger recordings: 
https://support.reolink.com/hc/en-us/articles/900000625763-What-is-CGI-API 
https://support.reolink.com/hc/en-us/article_attachments/900001038146/CGI_command.pdf 

Thanks for looking into this, I guess I will trigger recordings with the reolink app on my phone then.
