### ISSUE TITLE
no access to path for "Take snapshot"

### ISSUE THREAD

**Issue by benjabievres** [fwestenberg/reolink_dev#210]
Hi,

When i use the "Call a Service" => "Take a snapshot", I get a "No access to Path" error. Would it be possible to give a sample of the way to configure filename? 
I have the same kind of error for Video Recording.

Thanks

**Comment by chiefcomm** [comment]
Try the config below it works for me

        service: camera.snapshot
        target:
          entity_id: camera.[insert camera name]
        data: 
          filename: '/config/www/camera_roll/camera_{{ now().strftime("%Y%m%d-%H%M%S") }}.jpg'

**Comment by benjabievres** [comment]
> Try the config below it works for me
> 
> ```
>     service: camera.snapshot
>     target:
>       entity_id: camera.[insert camera name]
>     data: 
>       filename: '/config/www/camera_roll/camera_{{ now().strftime("%Y%m%d-%H%M%S") }}.jpg'
> ```

Thank you, it works perfectly!!

Regards

Ben
