### ISSUE TITLE
Camera Pan & Tilt

### ISSUE THREAD

**Issue by bend** [fwestenberg/reolink_dev#23]
Hi, 
Reolink E1 camera can be paned and tilted. Are you planning to add this functionality or is there a way to do it already in HA ? 

Thank you

**Comment by silfa718** [comment]
Just setup a RLC-423 which supposts ptz. Any help I can provide to add ptz control?

**Comment by silfa718** [comment]
I was able to use a restful command to get my camera to move to the preset locations I saved in the camera.

Not sure if that would help in getting ptz added.

**Comment by Klex1404** [comment]
It would be great to be able to set the PTZ position with a simple command to this great component!
I tried with a rest command but the token thing is difficult.

**Comment by fwestenberg** [comment]
Please check v0.8. Should be available now!
