### ISSUE TITLE
reolink_dev integration stop working 

### ISSUE THREAD

**Issue by MiAutomations** [fwestenberg/reolink_dev#238]
Hello 

During some time I have this integrationworking without any problem, but recently i start facing this issue 

![image](https://user-images.githubusercontent.com/47602733/127926556-544dbcf9-b7b9-4ab2-96e8-16efbca5667c.png)

With following log 

Logger: homeassistant.config_entries
Source: helpers/network.py:116
First occurred: 10:27:32 PM (1 occurrences)
Last logged: 10:27:32 PM

Error setting up entry Reolink C1 for reolink_dev
Traceback (most recent call last):
  File "/config/custom_components/reolink_dev/__init__.py", line 77, in async_setup_entry
    push = hass.data[DOMAIN][base.push_manager]
KeyError: 'push_manager-B0411D1FD780'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 293, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/reolink_dev/__init__.py", line 86, in async_setup_entry
    await push.subscribe(base.event_id)
  File "/config/custom_components/reolink_dev/base.py", line 302, in subscribe
    get_url(self._hass, prefer_external=False),
  File "/usr/src/homeassistant/homeassistant/helpers/network.py", line 116, in get_url
    raise NoURLAvailableError
homeassistant.helpers.network.NoURLAvailableError

--------------------------------------------------------------------------------------------------------------------------------

Logger: libav.rtsp
Source: components/stream/worker.py:338
First occurred: 10:27:16 PM (3 occurrences)
Last logged: 10:27:33 PM

Too short data for FU-A H.264 RTP packet

I alredy try do remove/disable add the camera again without sucess for now 

Can you please help me in oder to solve this issue? 

Thank you in advance for your support and best regards

**Comment by MiAutomations** [comment]
Just to share more info about this issue I'm using the v0.19 version reolink dev integration 
HA version - Home Assistant 2021.7.4

I just try with other camera model and the error persist... I'm not able to use this integration for now ...

**Comment by MiAutomations** [comment]
Hello @fwestenberg

Can you please help me in order to solve this issue ?

Thank you

**Comment by MiAutomations** [comment]
The issue may be is related to the costume integration 

[https://github.com/home-assistant/core/issues/54394](url) 

Any help in order to solve this issue ? Thank you

**Comment by HaxxHaris** [comment]
Hello,

I just bought Reolink E1 Zoom and am trying to integrate it into Home Assistant but get the same error: /

**Comment by Malvu** [comment]
Hello,

I ave Reolink E1 Zoom and am trying to integrate it into Home Assistant but get the same error: /

**Comment by HaxxHaris** [comment]
> Hello,
> 
> I ave Reolink E1 Zoom and am trying to integrate it into Home Assistant but get the same error: /

Hi Malvu,

I had the same problem as you, managed to solve this by filling in External URL and Internal URL under Configuration -> General

**Comment by Malvu** [comment]
> Hi Malvu,
> 
> I had the same problem as you, managed to solve this by filling in External URL and Internal URL under Configuration -> General

thank you for your answer, but the worry is still present

**Comment by MiAutomations** [comment]
> > Hi Malvu,
> > I had the same problem as you, managed to solve this by filling in External URL and Internal URL under Configuration -> General
> 
> thank you for your answer, but the worry is still present

Yes I Still facing the same erro also 

Thank you

**Comment by MiAutomations** [comment]
Hello Any news about this ?

Does anyone please have a ideia how to solve this? 

Thank you

**Comment by MiAutomations** [comment]
I just reinstall the home assistant, restore the backup and the problem persist 😐

I appreciate some help in order to try solve this issue

Thank you and best regards

**Comment by MiAutomations** [comment]
Hello 

Any news about this issue that I'm facing?

I update to the last version available and I still have the same issue ...  

Thank you and best regards

**Comment by fwestenberg** [comment]
Did you check #222 ?

**Comment by MiAutomations** [comment]
> Did you check #222 ?

Great thank you now is working again 

Thank you for your support and best regards
