### ISSUE TITLE
Config flow could not be loaded

### ISSUE THREAD

**Issue by rzulian** [fwestenberg/reolink_dev#239]
Hi,
I'm trying to add the integration, but, after a long wait  with a popup saying "PLease wait while the installation is being installed", I'm getting "Config flow could not be loaded".
I've restarted the server twice, but still doesn't work. Any clue on what to check?

**Comment by genebean** [comment]
Just got my cameras and am experiencing this too while trying to do initial setup.

**Comment by k2xl** [comment]
Encountering this trying to set up. 

core-2021.11.3
Home Assistant OS 6.6

**Comment by k2xl** [comment]
Note - Rebooting host for home assistant resolved this for me.

**Comment by cpainchaud** [comment]
there is a template to follow when you create a ticket. 


Closed until better infos provided
