### ISSUE TITLE
Feature request: Activate local SD recording

### ISSUE THREAD

**Issue by TPMunster** [fwestenberg/reolink_dev#246]
Hi and thank you for a great integration!

Would it be possible to implement a feature to activate local recording on the camera's internal SD card?
It would be preferable to activate recording upon a trigger activation, e.g. a external motion sensor or triggered alarm.

**Comment by cpainchaud** [comment]
If I am not mistaken it does exist in current version of the product. (I am using it) Please @TPMunster  check and close this issue.

**Comment by TPMunster** [comment]
@cpainchaud the camera itself has local SD recording. I can toggle whether it is activated or not from Home Assistant. But, when activated the camera records on its SD card when it detects motion in its own image - not based on e.g. an automation.

I cannot seem to fire a "camera.record.local" action, but please do guide me if you have it working?! 🙏 

Thank you in advance.

**Comment by cpainchaud** [comment]
this is a setting that you must configure in the camera application from your smartphone. You want to configure the Schedule menu : disable everything in Timer section and select what you want in Alarm section.

This will not be added to this integration because HA is not meant to be a device configurator. Only what is useful for automation will be implemented in my opinion.

Current "SD Card recording" button will enable/disable recording feature entirely but you will still need to configure the "Schedule" part within your camera directly

**Comment by TPMunster** [comment]
I am not quite sure i'm explaining myself correctly. 
Perhaps if I explain the scenario it would make more sense:

Here goes:
If the Alarm is triggered in my house, I would like to tell the camera to start recording - locally. How do I achieve this with the current integration?
It should **not** record at any other time.

**Comment by fwestenberg** [comment]
You should create an automation, triggered by the alarm. The automation should turn on the recording switch. Also create an automation to turn it off again after x minutes for example.

**Comment by cpainchaud** [comment]
Exactly yes

**Comment by TPMunster** [comment]
Well, that is not how it works IRL. When you toggle that switch you toggle the setting within the camera, and not starting a recording. It will still only start recording if it detects motion within its picture.

Here is my documentation:


**Activated Recording switch in HA @ 12:07:**
<img src="https://user-images.githubusercontent.com/68892864/135249687-d8cc7cf6-639a-41ba-bd90-d108cd509cbc.png" width="40%">

**Screenshot from the Reolink app, showing no recording on the timestamp of my activation of switch in HA.**
<img src="https://user-images.githubusercontent.com/68892864/135250006-3bda1211-dadf-456a-95d5-1287936f32a5.jpg" width="40%">

**Instead it toggles the camera setting within itself, and still only records when motion is detected** 
<img src="https://user-images.githubusercontent.com/68892864/135250342-95bd2d2c-dd0b-4a6a-8388-6225f3333dc5.png" width="40%">

**Comment by cpainchaud** [comment]
Edit record scheduling to enable everything in the Timer tab

**Comment by TPMunster** [comment]
@cpainchaud @fwestenberg ABSOLUTLY correct! Thanks a million, it works as intended! 🙏
