### ISSUE TITLE
Can’t add repo to HA

### ISSUE THREAD

**Issue by FabioEight** [fwestenberg/reolink_dev#252]
Hello,
Following the guide to install the plugin, I’m unable to add the repo on Home Assistant: 

Invalid Add-on repository!

I tried to add different repos, with success.
Thanks.

**Comment by olaoups** [comment]
Hello! I've exactly the same problem. Reolink e1 zoom + HA 2021.8.8
Thanks!

**Comment by olaoups** [comment]
OK I answer myself:

It's not an add-on repo!!! 
So...
1. Install HACS, see https://hacs.xyz/docs/installation/installation/
2. Follow the instructions on https://github.com/fwestenberg/reolink_dev
