### ISSUE TITLE
2021.9: Breaking change in camera

### ISSUE THREAD

**Issue by andriej** [fwestenberg/reolink_dev#254]
https://rc.home-assistant.io/blog/2021/08/25/release-20219/ - in breaking changes there's a note for custom camera components developers, about adding a height and width

**Comment by ijustlikeit** [comment]
Reolink cameras are sending warning messages.  This needs to be looked at.

Logger: homeassistant.components.camera
Source: components/camera/__init__.py:465
Integration: Camera (documentation, issues)
First occurred: 9:10:02 PM (3 occurrences)
Last logged: 9:15:51 PM

The camera entity camera.backyard does not support requesting width and height, please open an issue with the integration author
The camera entity camera.frontdoor does not support requesting width and height, please open an issue with the integration author
The camera entity camera.westside does not support requesting width and height, please open an issue with the integration author

**Comment by andriej** [comment]
Details are in release note:
![image](https://user-images.githubusercontent.com/6303489/131796827-91b8ebfb-5929-4b01-9047-e313b34447b6.png)

**Comment by cpainchaud** [comment]
should be fixed with PR https://github.com/fwestenberg/reolink_dev/pull/274 . Waiting for author to issue a release

**Comment by fwestenberg** [comment]
Just released v0.20!

**Comment by ijustlikeit** [comment]
Thanks for your work on this!

**Comment by fwestenberg** [comment]
Thank you too!
