### ISSUE TITLE
How to stream to chromecast?

### ISSUE THREAD

**Issue by IsaTTeN** [fwestenberg/reolink_dev#26]
Hi @fwestenberg!

Do you know if it´s possible to use the service camera.play_stream with your custom component?.

I would like to send eventually the cameras to my chromecast, but I can´t do it actually

I have this in my configuration.yaml:
`# Example configuration.yaml entry
stream:`

But I getan API error if I try to send the camera to chromecast

Best regards and thanks for your work, I can´t live without your custom component

**Comment by fwestenberg** [comment]
Hello @IsaTTeN, thanks for using the custom component. What error do you get? I don't use the chromecast stream, but maybe I can solve this with your help.
