### ISSUE TITLE
Unable to change Integration Parameters

### ISSUE THREAD

**Issue by colinnewman2000** [fwestenberg/reolink_dev#277]
When trying to change integration parameters, clicking submit simply results in an error message stating 'User Input Malformed .....

![Screenshot 2021-09-24 at 15 21 33](https://user-images.githubusercontent.com/83005778/134690639-07f0ba0e-7f68-4704-8f0f-053c83414d46.jpg)
.

Even if nothing is changed the error persists.

Not possible to change anything !!

**Comment by AbsolutJohan** [comment]
Seems you have to input something in the field “custom thumbnail path”. Try / and then submit
