### ISSUE TITLE
Camera Connection Error

### ISSUE THREAD

**Issue by feetie** [fwestenberg/reolink_dev#28]
(Thank you for creating this project!) 

I have three Reolink cameras that I formerly streamed to my front end via ffmpeg platform with rtsp input.  I just rebuilt my HA with the latest Hassio image and discovered your project. I was able to get my two C2 PTZ cameras working fine but the third bullet RLC-410S cam is not connecting. From log:

**Error translating login response to json
10:40 AM custom_components/reolink_dev/ReolinkPyPi/camera.py (ERROR)**

**Exception while calling Reolink camera API at ip 192.168.1.114
10:40 AM custom_components/reolink_dev/ReolinkPyPi/camera.py (ERROR)**

The credentials are exactly the same as the other cameras, have not changed and worked previously. This is my configuration.yaml entry (I removed the other cameras) :

camera:
- platform: reolink_dev
  host: 192.168.1.114
  username: admin
  password: mypassword
  name: Backyard
  stream: main
  protocol: rtmp 
  scan_interval: 5

Restarting camera and HA have no effect. I also changed the protocol to rtsp just to see if that made a difference but get same errors. Any suggestions? 

Thanks

**Comment by fwestenberg** [comment]
Sorry for my late response! If I look at the code, the camera should give a json response after correct login. The error you logged only appears when the json is not valid. So in order to find out what's happening, can you provide me the response (from the browser) of the login command? The request should look: 

`body = [{"cmd": "Login", "action": 0, "param": {"User": {"userName": username, "password": password}}}]`

Thanks!

**Comment by scstraus** [comment]
I have this problem too. It seems to come from the app being connected and streaming the cameras. When it is, it seems like the component no longer can connect to the camera and login. It would be good to have an availability sensor to tell when this is happening and when it's not, as I use a conditional card to show the camera, it would be good to only show it when it's actually working. I will open an issue for that.

**Comment by keith-b-c** [comment]
> Sorry for my late response! If I look at the code, the camera should give a json response after correct login. The error you logged only appears when the json is not valid. So in order to find out what's happening, can you provide me the response (from the browser) of the login command? The request should look:
> 
> `body = [{"cmd": "Login", "action": 0, "param": {"User": {"userName": username, "password": password}}}]`
> 
> Thanks!

I have the same problem, how do I go about entering the above code?

**Comment by IvanPenyaHuguet** [comment]
I think he wants the response of the login. One way to do it is with [Postman](https://www.postman.com), you have to do a POST request to http://YOUR_CAM_IP/cgi-bin/api.cgi with one param key cmd and value of login and a raw json body as given changing the username and password for yours:

`[{"cmd": "Login", "action": 0, "param": {"User": {"userName": username, "password": password}}}]`

Two photos to understand how to do it in postman, click send and paste here the body response.

![Capture1](https://user-images.githubusercontent.com/65863620/90989650-b655f680-e59b-11ea-8c4b-fece76bdf302.JPG)
![Capture2](https://user-images.githubusercontent.com/65863620/90989654-bb1aaa80-e59b-11ea-9e9b-9f49105c2960.JPG)

The response has to look something like this: 
`[
   {
      "cmd": "Login",
      "code": 1,
      "error": {
         "detail": "login failed",
         "rspCode": -7
      }
   }
]`

**Comment by fwestenberg** [comment]
Please check v0.8.
