### ISSUE TITLE
Add NVR support

### ISSUE THREAD

**Issue by gregoryduckworth** [fwestenberg/reolink_dev#3]
At the moment cameras are supported but it would be nice to allow cameras to be interacted with through an NVR.

An interim fix I use with the generic camera can be found here - https://community.home-assistant.io/t/reolink-nvr-stream-or-snapshots-please-i-need-help-seeing-them-on-hassio/116030/4 

Happy to assist on this.

**Comment by fwestenberg** [comment]
What is not working here? You mean the stream and image URL is different?

**Comment by gregoryduckworth** [comment]
Due to the way the rtsp feeds are constructed, the cameras do not have individual IP addresses, which means you can't access multiple cameras.

An example of the addresses:
```
camera_01: rtsp://admin:password@192.168.1.100:554/h264Preview_01_sub
camera_02: rtsp://admin:passwed@192.168.1.100:554/h264Preview_02_sub
```

**Comment by gregoryduckworth** [comment]
Another thing of note in the above urls is `h264Preview_01_sub` refers to a sub stream (lower quality) as opposed to `h264Preview_01_main` which is the main stream.

**Comment by bakasdim** [comment]
Just discovered this component and it's great!
Nvr support would be great in the future! Cheers

**Comment by begicj** [comment]
For NVR is necessary to specify channel number. For example:

if we want motion detection to work properly over NVR then we need to send api command: http: //IP_of_NVR/cgi-bin/api.cgi?  cmd=GetMdState&token=someletters&user=user&password=mypass with POST method not GET and with body: [{"cmd": "GetMdState", "param": {"channel": 0}}] (for first channel on NVR is:0, for second channel is:1...) and we will get response: 
[
  {
    "cmd": "GetMdState",
    "code": 0,
    "value": {
      "state": 0
    }
  }
]

It is possible to combine motion detection on multiple channels with one command: http: //IP_of_NVR/cgi-bin/api.cgi?  cmd=GetMdState&token=someletters&user=user&password=mypass with POST method not GET and with body [{"cmd": "GetMdState","param":{"channel":0}};{"cmd": "GetMdState","param":{"channel":1}}]
 and get results:
[
   {
      "cmd" : "GetMdState",
      "code" : 0,
      "value" : {
         "state" : 0
      }
   },
   {
      "cmd" : "GetMdState",
      "code" : 0,
      "value" : {
         "state" : 0
      }
   }
]
For each channel and if there is no camera on some channel we will get

[
   {
      "cmd" : "GetMdState",
      "code" : 0,
      "value" : {
         "state" : 0
      }
   },
   {
      "cmd" : "GetMdState",
      "code" : 1,
      "error" : {
         "detail" : "get config failed",
         "rspCode" : -12
      }
   },
   {
      "cmd" : "GetMdState",
      "code" : 0,
      "value" : {
         "state" : 0
      }
   }
]

I have disconnected camera on channel 2 for this test

**Comment by fwestenberg** [comment]
Thanks for all the info! I think NVR needs some different approach. Or have you planned to add an configuration item for each stream? I just added two parameter for the stream (main/sub) selection and one for the protocol (rtmp/rtsp). So would it help you if I add a parameter for the stream and motion channel?

**Comment by begicj** [comment]
It will be awesome if You can add channel parameter for stream and motion so we can add configuration for each camera in home assistant

**Comment by fwestenberg** [comment]
Please let me know if this is a working solution for you. As I don't have a NVR recorder, I don't know if e-mail alerts, FTP and IR-lights are also controlled this way? For changing the IR light of a specific camera for example, I'll probably need to add the channel also.

**Comment by begicj** [comment]
Stream works 
Motion detection works 
FTP not tested 
Email not tested 
Ir lights not working, 

Log Details (ERROR)
Fri Jan 03 2020 22:03:30 GMT+0100 (CET)

'value'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 133, in handle_call_service
    connection.context(msg),
  File "/usr/src/homeassistant/homeassistant/core.py", line 1235, in async_call
    await asyncio.shield(self._execute_service(handler, service_call))
  File "/usr/src/homeassistant/homeassistant/core.py", line 1260, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 205, in handle_service
    self._platforms.values(), func, call, service_name, required_features
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 336, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 358, in _handle_service_platform_call
    await getattr(entity, func)(**data)
  File "/usr/src/homeassistant/homeassistant/components/template/switch.py", line 190, in async_turn_on
    await self._on_script.async_run(context=self._context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 190, in async_run
    await self._handle_action(action, variables, context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 273, in _handle_action
    await self._actions[_determine_action(action)](action, variables, context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 355, in _async_call_service
    context=context,
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 97, in async_call_from_config
    domain, service_name, service_data, blocking=blocking, context=context
  File "/usr/src/homeassistant/homeassistant/core.py", line 1235, in async_call
    await asyncio.shield(self._execute_service(handler, service_call))
  File "/usr/src/homeassistant/homeassistant/core.py", line 1262, in _execute_service
    await self._hass.async_add_executor_job(handler.func, service_call)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/reolink_dev/camera.py", line 114, in handler_enable_ir_lights
    entity.enable_ir_lights()
  File "/config/custom_components/reolink_dev/camera.py", line 272, in enable_ir_lights
    if self._reolinkSession.set_ir_lights(True):
  File "/config/custom_components/reolink_dev/ReolinkPyPi/camera.py", line 248, in set_ir_lights
    body = [{"cmd":"SetIrLights","action":0,"param": self._ir_settings["value"] }]
KeyError: 'value'

**Comment by gregoryduckworth** [comment]
Finally got round to looking at this, however I get the following errors:
![image](https://user-images.githubusercontent.com/2647926/74261714-8fb52a00-4cf3-11ea-8ea4-4684a4435cf4.png)

**Comment by gregoryduckworth** [comment]
Looking through the response from Postman with the url `http://<IP ADDRESS>/cgi-bin/api.cgi?cmd=Snap&channel=0&rs=<RANDOM STRING>&user=<USERNAME>&password=<PASSWORD>` I get the response. So thinking the url isn't constructed correctly. I will do some more investigation.

```<html>
    <head><title>Document Error: Not Found</title></head>
    <body>
        <h2>Access Error: Not Found</h2>
        <p>CGI program file does not exist</p>
    </body>
</html>
```

**Comment by gregoryduckworth** [comment]
I have a support request open with Reolink, so hopefully can get to the bottom of it.

**Comment by gregoryduckworth** [comment]
After lots of emails with support, it looks like my NVR doesn’t support the functionality!

**Comment by ukscarface** [comment]
Hello there is approximately 10 seconds lag on my system? is there any way to change this?

**Comment by fnittoli** [comment]
> Finally got round to looking at this, however I get the following errors:
> ![image](https://user-images.githubusercontent.com/2647926/74261714-8fb52a00-4cf3-11ea-8ea4-4684a4435cf4.png)

I have the same issues, did you solve? 
My NVR is :

RLN8-410
build 1805240
firmware: 2.0.0.4498_1601_18052408100

**Comment by KameDomotics** [comment]
Hi, i have a Reolink RLN8-410-E NVR with v.2.0.0.249_20011608101 firmware (2020).

I have installed Reolink integration in HACS, and in configurarion.yaml I have configurated this:

Copy to clipboard
camera:
- platform: reolink_dev
  host: 192.168.1.16   
  username: admin
  password: my password
  name: CAM GIARDINO
  stream: sub
  protocol: rtsp
  channel: 01
  scan_interval: '00:00:05' 

Now I can see entity “camera.cam_giardino” (without entity icon, only name), but streaming don’t start.

I set only point 1 (I’m non intrested about motion detection)

**Comment by fwestenberg** [comment]
@gregoryduckworth Can you please check using network capture in your browser, if your NVR has some API which tells us what channels are available? My camera's only have 1 channel of coure. And I have no NVR to test this. Thanks!

**Comment by gregoryduckworth** [comment]
@fwestenberg - unfortunately I have spoken to Reolink and my NVR doesn't support the capability 😢  but others might be able to help with that.

**Comment by spripe** [comment]
Is Reolink RLN8-410 8-channels supported?

**Comment by fwestenberg** [comment]
I won't say it's _not_ supported. The parameters (like channel) are in the configuration, but I don't own a NVR so it's hard to tell it has full support. You should definitely give it a try, and report back what works (and what don't).
