### ISSUE TITLE
Failed to connect with the camera - NVR

### ISSUE THREAD

**Issue by KennethEgholm** [fwestenberg/reolink_dev#300]
**Describe the bug**
When trying to install the integration, I get "Failed to connect with the camera".
The IP I am pointing to is the IP of my Reolink NVR.

**Screenshots**
![image](https://user-images.githubusercontent.com/48353597/136585045-3cb03986-8972-4df1-9ad5-e994657ca605.png)

**Environment:**
 - Reolink NVR 410

**Comment by MacL3an** [comment]
Thank you @KennethEgholm, `internal_url` did the trick! 🎉

**Comment by leroyloren** [comment]
For me, it is still the latest works version 0.22.

0.26 cannot be connected to either NVR or camera directly.

All the latest firmware, including the completed internal_url

It always ends that the webhook cannot be renew.
