### ISSUE TITLE
RLC-520A Sensor is unavailable

### ISSUE THREAD

**Issue by milandzuris** [fwestenberg/reolink_dev#315]
Camera Reolink RLC-520A, Person Vehicle and Pets Sensor is unavailable all the time, only working motion sensor.

![image](https://user-images.githubusercontent.com/42905545/137529631-84fc26f7-5767-41bb-a9ca-bbb16340f619.png)

**Comment by cpainchaud** [comment]
Closed until proper feedback and template is provided

**Comment by milandzuris** [comment]
> ticket template

what exactly do you mean, or where can I find it.

**Comment by cpainchaud** [comment]
when you open a new issue, it proposes you to fill in a template.
