### ISSUE TITLE
possible to add spotlight as a entity to cameras such as  RLC-811A 

### ISSUE THREAD

**Issue by rchiileea** [fwestenberg/reolink_dev#323]
is it even possible to get this entity showing, via the reolink app there is control?

**Comment by pepsinio** [comment]
If this is possible, it will be the only reason to keep this addon :)

**Comment by ovid-io** [comment]
I've opened this [feature request](https://github.com/fwestenberg/reolink/issues/58) to the library to add support with a link to some documentation I found how to achieve.

I've managed to make it work with a shell script that issues a curl request to the camera itself like so:
```
shell_command:

  cam_spotlight_on: >-
    curl -X POST 'http://192.168.1.100/cgi-bin/api.cgi?user=ha&password=password' \
         -d '[{ "cmd": "SetWhiteLed", "param": { "WhiteLed": { "bright": 20, "channel": 0, "mode" : 3, "state": 1 }}}]'
  
  cam_spotlight_off: >-
    curl -X POST 'http://192.168.1.100/cgi-bin/api.cgi?user=ha&password=password' \
         -d '[{ "cmd": "SetWhiteLed", "param": { "WhiteLed": { "bright": 20, "channel": 0, "mode" : 0, "state": 0 }}}]'
```

**Comment by rchiileea** [comment]
defo would be a usefull feature, especially with the garden one. I have a switch right by back door I could assign to this too

**Comment by cpainchaud** [comment]
please try 0.40 and let us know

**Comment by rchiileea** [comment]
Perfect it works how I wanted it, actually going to use this as a quick light to light up shed rather than turn on all garden lights magnifico
