### ISSUE TITLE
Cant add camera after 0.33 update

### ISSUE THREAD

**Issue by johnnysmithy852456** [fwestenberg/reolink_dev#341]
Hi
I have two cameras same firmware, one loads with 0.33 on port 443 and the other one keeps coming up with error at the add screen.

HA Supervisor 2021.10.6
![Screen Shot 2021-10-26 at 11 05 23 am](https://user-images.githubusercontent.com/60836292/138788602-086dbcc6-1e4a-45d9-9ec0-5a172c1fa0e6.png)

**Comment by INVADIA666** [comment]
hi mate , I'm having the same issue , I bought a Duo PoE, it works perfectly in the app but I receive the same unexpected error in home assistant using the reolink integration.
