### ISSUE TITLE
Unable to stream on iPhone App or Safari

### ISSUE THREAD

**Issue by timknowlden** [fwestenberg/reolink_dev#346]
Hi, Since latest update I am unable to stream on my iPhone, I have restarted Device, Refreshed Cache, Deleted and Re-installed the HA app. The Thumbnail opens but iPhone then freezes up and when it respoonds I have to crash the app.

It works fine on my wifes iPhone and on my Macbook in safari.

I have tried changing from RTMP to RTSP, h264 to h265 (a typo in the about me by the way), sub or main stream. 

iPhone on iOS 15.1
HA 2021.10.6
Reolink IP camera installed by HACS v0.34
Camera E1 Zoom

**Comment by timknowlden** [comment]
Am I alone with this issue? 

The live view works in a custom button card. but not when opening the stream?

**Comment by d3m3trius** [comment]
looks like the same problem as # 278

**Comment by timknowlden** [comment]
After changing the camera stream resolution, its working.

**Comment by svsolopov** [comment]
> After changing the camera stream resolution, its working.

What resolution you set ?

**Comment by timknowlden** [comment]
Any resolution works. But changing the resolution from what it was in originally made it work.

**Comment by timknowlden** [comment]
![Uploading B1003AED-EB5C-47B5-BB60-517D825788C5.png…]()
