### ISSUE TITLE
Person detection entity turning off too quickly

### ISSUE THREAD

**Issue by Bruskey** [fwestenberg/reolink_dev#357]
RLC-810a camera recently upgraded to firmware version v3.0.0.494 and since then, the person detection entity state changes to "detected" when a person is detected as expected, but it quickly changes to "clear" within a few seconds, even though a person is still clearly in the view and moving around. With previous firmware version v3.0.0.136 the entity will stay on until the person leaves. Nothing else changed since upgrading firmware version.

HA 2021.10.4

I have 2x 810a cameras, one on the older firmware which behaves as i would expect, and downgrading firmware back to the older version fixes this

**Comment by cpainchaud** [comment]
Hi,

 It's the new way that Reolink has implemented their firmware, they clear the flag after 5 seconds and they don't give a f$ck about our opinion.

**Comment by Bruskey** [comment]
Hmm ok. How has nobody else complained about this though? Ive searched through everything and havent found anyone mentioning this.

**Comment by cpainchaud** [comment]
The fact is that if you want to build automation or get alerts, it shouldn't be a problem if the "ON" time is short so most people won't notice it.

I asked Reolink to go back to previous norms and/or include timestamps in events but they dont seem to care much

**Comment by Bruskey** [comment]
Ok. So how does that logic actually work then. If it goes off after 5 seconds, how is the next motion event captured? My expectation would be then that after it going off for 5 seconds it would come back on straight away as there would be a new event? In my testing it appeared very random as to when it came back on.

**Comment by cpainchaud** [comment]
that is their 'magic'. our integration will update whenever it receives a
webhook call from them. They have failed to provide the new algorithm they
are using. It is truly annoying ! :)
