### ISSUE TITLE
Issue to load de image from the camera 

### ISSUE THREAD

**Issue by nunokaneco** [fwestenberg/reolink_dev#36]
Hello 

I'm trying to put this to work but when I try I can't load the image as you can see on the image attch (link) 

[https://imgur.com/zpcWteG](url) 

Other doubt is regarding this point

Can you please let me know where is this code to be placed? is on a new file with other name ? Is to be placed on the configuration.yaml or in the ui-lovelace.yaml

4 - 
Create email, FTP upload and infrared light buttons:
platform: template
switches:
  camera_frontdoor_email:
    value_template: "{{ is_state_attr('camera.frontdoor', 'email_enabled', true) }}"
    turn_on:
      service: camera.enable_email
      data:
        entity_id: camera.frontdoor
    turn_off:
      service: camera.disable_email
      data:
        entity_id: camera.frontdoor
    icon_template: >-
      {% if is_state_attr('camera.frontdoor', 'email_enabled', true) %}
        mdi:email
      {% else %}
        mdi:email-outline
      {% endif %}
        
  camera_frontdoor_ftp:
    value_template: "{{ is_state_attr('camera.frontdoor', 'ftp_enabled', true) }}"
    turn_on:
      service: camera.enable_ftp
      data:
        entity_id: camera.frontdoor
    turn_off:
      service: camera.disable_ftp
      data:
        entity_id: camera.frontdoor
    icon_template: >-
      {% if is_state_attr('camera.frontdoor', 'ftp_enabled', true) %}
        mdi:filmstrip
      {% else %}
        mdi:filmstrip-off
      {% endif %}
      
  camera_frontdoor_ir_lights:
    value_template: "{{ is_state_attr('camera.frontdoor', 'ir_lights_enabled', true) }}"
    turn_on:
      service: camera.enable_ir_lights
      data:
        entity_id: camera.frontdoor
    turn_off:
      service: camera.disable_ir_lights
      data:
        entity_id: camera.frontdoor
    icon_template: >-
      {% if is_state_attr('camera.frontdoor', 'ir_lights_enabled', true) %}
        mdi:flashlight
      {% else %}
        mdi:flashlight-off
      {% endif %}

Thank you in advance for your support and best regards

**Comment by fwestenberg** [comment]
Hi Roger, 

The lines should be in your configuration.yaml. Also you can split up your configuration, as described here: https://www.home-assistant.io/docs/configuration/splitting_configuration/

From the info provided I cannot say why the camera is not working. Any logs?

**Comment by robmack21c** [comment]
I think I have the solution, basically there's a minor update needed on the readme.md, this is a great tool and its working well for me now.  The readme says that the name is optional, but I've found it's key to the process.  See below the readme:
`camera:
- platform: reolink_dev
  host: IP_ADDRESS
  username: admin
  password: YOUR_PASSWORD
  name: camera (optional, default Reolink Camera)
  stream: main or sub (optional, default main)
  protocol: rtmp or rtsp (optional, default rtmp)
  channel: NVR camera channel (optional, default 0)
  scan_interval: 5 (optional, default 30s)`

When you create the camera using the example code, name it frontdoor and ensure it's frontdoor on the card too.  So the entity referenced on the cards and in the switch needs to match and it needs to match the name on the camera
`camera:
- platform: reolink_dev
  host: 192.168.0.31
  username: admin
  password: password
  name: frontdoor`

**Comment by fwestenberg** [comment]
Strange! In the platform schema i put:
`DEFAULT_NAME = "Reolink Camera"`
`vol.Optional(CONF_NAME, default=DEFAULT_NAME): cv.string,`

So without the complete last line:
```
- platform: reolink_dev
  host: 192.168.0.31
  username: admin
  password: password
````
it should work... And the card only has the title, no name option at all. What do you mean by: 
> and ensure it's frontdoor on the card too.

**Comment by fwestenberg** [comment]
Please check v0.8. All configuration goes via the flow now.

**Comment by MiAutomations** [comment]
> Please check v0.8. All configuration goes via the flow now.

Hello Can you please explain me what you mean with the via flow ? 

Thank you and best regards

**Comment by fwestenberg** [comment]
Sure, go to Configuration (side menu) -> Integrations -> Add, and search for Reolink.

**Comment by MiAutomations** [comment]
> Sure, go to Configuration (side menu) -> Integrations -> Add, and search for Reolink.


Great thank you is now working, can you please also let me know where I can configure the FTP, email and the recording paths for video and audio and de credentials for this integration ?

Thank you and best regards

**Comment by fwestenberg** [comment]
I'm not sure if I get you right. All of these options are in the WebUI of your camera (path and stuff). What would you like to do?

**Comment by MiAutomations** [comment]
> I'm not sure if I get you right. All of these options are in the WebUI of your camera (path and stuff). What would you like to do?

The ideia is to configure this for the correct path for exempla for a ftp server or for NAS is this possible ?

**Comment by fwestenberg** [comment]
You want to send a picture or video to the NAS? This is possible in the WebUI of the camera. Configure the camera first, and with the Home Assistant switches you can enable/disable the upload.

**Comment by MiAutomations** [comment]
> You want to send a picture or video to the NAS? This is possible in the WebUI of the camera. Configure the camera first, and with the Home Assistant switches you can enable/disable the upload.

Ok thank you now I understand great and thank you for your work !!
