### ISSUE TITLE
Entity - State not updating 

### ISSUE THREAD

**Issue by beginnersguide** [fwestenberg/reolink_dev#368]
Hey,
the state is not updating whether which entity I am using (binary_sonsors).  Only after a restart of HA the state is updated (for example (sensor.cameraname_last_event)

Setup:
HA: core-2021.11.4 ; supervisor-2021.10.8
HACS: 1.17.2
Home Assistant Reolink addon: v0.37
Camera: RLC-510A

**Comment by cpainchaud** [comment]
please provide logs: https://github.com/fwestenberg/reolink_dev/blob/master/TSHOOT.md

**Comment by cpainchaud** [comment]
please try v0.39 and/or provide logs
