### ISSUE TITLE
RTMP stream does not open after upgrading to v0.40

### ISSUE THREAD

**Issue by boozelclark** [fwestenberg/reolink_dev#377]
**Describe the bug**
The stream no longer opens after upgrading to v0.40

The log gives the errors

Logger: libav.rtmp
Source: components/stream/worker.py:412
First occurred: 15:21:57 (11 occurrences)
Last logged: 15:22:58

Detected librtmp style URL parameters, these aren't supported by the libavformat internal RTMP handler currently enabled. See the documentation for the correct way to pass parameters.

followed by

Logger: homeassistant.components.stream.worker
Source: components/stream/worker.py:414
Integration: Stream (documentation, issues)
First occurred: 15:21:57 (4 occurrences)
Last logged: 15:21:58

Error opening stream rtmp://****:****@MyPassword
Error opening stream rtmp://192.168.1.202:1935/bcs/channel0_sub.bcs?channel= 0&stream=0&user=hass&password=MyPassword
Error opening stream rtsp://****:****@192.168.1.203:554/ h264Preview_01_sub

This is using an RLC810A on firmware v3.0.0.494

**Environment:**
Please provide useful information about your environment, like:
 - Home Assistant version 2021.11.4
 - RLC810A
 - Camera firmware number - v3.0.0.494

**Additional context**

**Comment by FelipeDamasio** [comment]
Same here

**Comment by 6Firewall6** [comment]
I am having the same issue after the update.

**Comment by cpainchaud** [comment]
oups, that was a glitch in the matrix :) try 0.41 in a few minutes, time for PYPI to cache the newer library version
