### ISSUE TITLE
Message in the logbook

### ISSUE THREAD

**Issue by Malvu** [fwestenberg/reolink_dev#378]
I'm certainly not the only one but I have this every time I try to integrate my Reolink E1 Zoom
![1](https://user-images.githubusercontent.com/46385414/144315625-e810ce01-7183-41d0-9ba0-dfe05bfa67be.jpg)

**Comment by odelma** [comment]
I can confirm that I see the same message in the log.

**Comment by cpainchaud** [comment]
please try version 0.42, courtesy of @ptyers

**Comment by FelipeDamasio** [comment]
Same here

**Comment by FelipeDamasio** [comment]
I updated to the 0.42 and this error persists:

Host: 192.168.1.55: Failed to get results for Search, JSON data was was empty?

**Comment by cpainchaud** [comment]
Wasn't that one there forever? The search/footage listing has always been buggy and chatty as far as I know.

**Comment by FelipeDamasio** [comment]
Yes, I believe it already appeared in previous versions... as well as the out-of-order

**Comment by Malvu** [comment]
Why close the topic the problem is not solved.

**Comment by Malvu** [comment]
Why close the topic the problem is not solved.
