### ISSUE TITLE
All controls missing after upgrade to v0.42

### ISSUE THREAD

**Issue by atryan81** [fwestenberg/reolink_dev#380]
**Describe the bug**
After upgrading to v0.42 from v0.38 all my controls stopped working eg: all switches for IR, Notifications, recording, etc. are no longer showing up in the integration.

**To Reproduce**
Confirmed issue with a fresh install of Home Assistant and Reolink addon v0.42 same issue controls are no longer showing up in integration.

**Expected behavior**
Controls available for use eg: IR, Notifications, recording, etc.

**Environment:**
Operating System
Core-2021.11.5
Supervisor-2021.10.8
Home Assistant OS 6.6
Reolink_dev: v0.42

Cameras: RLC-810A
Firmware: v3.0.0.494
NVR: RLN8-410
Firmware: v3.0.0.0.148

**Additional context**
rolled back to version v0.38 and all functionality has returned

**Comment by cpainchaud** [comment]
Hi, we need logs to understand what is going on. (https://github.com/fwestenberg/reolink_dev/blob/master/TSHOOT.md)
