### ISSUE TITLE
No motion from 811A 

### ISSUE THREAD

**Issue by Lieberkind72** [fwestenberg/reolink_dev#387]
Hi,

I have the Reolink 811A and just installed the integration from HACS.

when there is motion (ordinary, person and vehicle) i get notification from Reolink app, but no change in status in HA.

 Is there a way to fix this?

**Comment by almazikv** [comment]
Having the same problem with RLC-410.

**Comment by PetrStary** [comment]
Confirmed. Having 811A also. Once while testing I got a random Sirene.

**Comment by cpainchaud** [comment]
Closed until proper template is respected.

You can also enable better logging here https://github.com/fwestenberg/reolink_dev/blob/master/TSHOOT.md

**Comment by Lieberkind72** [comment]
> Closed until proper template is respected.
> 
> You can also enable better logging here https://github.com/fwestenberg/reolink_dev/blob/master/TSHOOT.md
 Please explain proper template.

**Comment by Lieberkind72** [comment]
Please explain proper template.

**Comment by gingemonster** [comment]
@Lieberkind72  he means when you raise the issue, fill out all the details the template shows like this:

![image](https://user-images.githubusercontent.com/703352/146421309-45c6038c-ff69-420e-bb19-b1280634ad0d.png)

**Comment by cpainchaud** [comment]
duplicate of https://github.com/fwestenberg/reolink_dev/issues/411
