### ISSUE TITLE
Invalid repository

### ISSUE THREAD

**Issue by pleinfinegrey** [fwestenberg/reolink_dev#393]
**Describe the bug**
When I add "https://github.com/fwestenberg/reolink_dev" to my homeassitant as custom repository, I get the message "Invalid Add-on repository!

**To Reproduce**
Steps to reproduce the behavior. Please provide the error from the log if possible.

**Expected behavior**
Repository added

**Screenshots**
<img width="322" alt="image" src="https://user-images.githubusercontent.com/79780880/144911147-766bfe70-7bb9-410d-996f-40a78dfca612.png">

**Environment:**
Please provide useful information about your environment, like:
 - Home Assistant version : core-2021.11.5 , supervisor-2021.10.8
 - Reolink camera model
 - Camera firmware number

**Additional context**

**Comment by mlinuxguy** [comment]
I have the same issue on a new install with very latest HA

**Comment by cpainchaud** [comment]
You are supposed to use HACS as explained in the readme.

**Comment by mlinuxguy** [comment]
That's exactly what I did.
Supervisor --> Add On Store --> Home Assistant Community Addons --> triple-dots in upper right --> ManageAddons (sub Home Assistant Community Adons)  --> Add (https://github.com/fwestenberg/reolink_dev) --> ERROR

**Comment by cpainchaud** [comment]
HACS is no Community Addons

**Comment by mlinuxguy** [comment]
I see that now.   Installing it.
