### ISSUE TITLE
A space " " character prevents playback of recorded clips from SD card

### ISSUE THREAD

**Issue by KruyKaze** [fwestenberg/reolink_dev#395]
Hello , and thanks for making this integration. I was unable to playback the SD recordings and looked at the logs . They show : 
`Error opening stream rtmp://REDACTED:1935/vod/Rec_20211208_065445_541_M.mp4?channel= 0&stream=0&token=REDACTED`
Note the space between "channel=" and "0" . When I removed that line and tried it on VLC it worked just fine.

I also do not see any thumbnails . Not sure it it's related.

**Environment:**

 - Home Assistant version 2021.10.5
 - Reolink camera model E1 ZOOM
 - Camera firmware number v3.0.0.247_21040708

**Comment by cpainchaud** [comment]
This code is producing it:
```python
stream_source = f"rtmp://{self._host}:{self._rtmp_port}/vod/{filename.replace('/', '%20')}?channel={self._channel}&stream=0&token={self._token}"
```
As you can see there is no space. What are the odds that said space is actually in your configuration/user input ?

**Comment by KruyKaze** [comment]
Thanks for the reply,
I just recently installed the camera and this is the extent of the configuration i have : 
![image](https://user-images.githubusercontent.com/70369/145261958-1c05990f-c254-4f91-bf25-d2b1c7526055.png)

I don't see where you would specify the channel number. Can you point me to where that would be? 
Thanks again

**Comment by thomasloven** [comment]
> This code is producing it:
> 
> ```python
> stream_source = f"rtmp://{self._host}:{self._rtmp_port}/vod/{filename.replace('/', '%20')}?channel={self._channel}&stream=0&token={self._token}"
> ```
> 
> As you can see there is no space. What are the odds that said space is actually in your configuration/user input ?

That's not what the code says, though.

```python
        stream_source = f"rtmp://{self._host}:{self._rtmp_port}/vod/{filename.replace('/', '%20')}?channel=\
                            {self._channel}&stream=0&token={self._token}"
```
The indentation causes the space.

[Helpful link to the actual code](https://github.com/fwestenberg/reolink/blob/main/reolink/camera_api.py#L659-L660)

**Comment by cpainchaud** [comment]
my eyes are hurting, I know where I got my copy/paste from now .......
