### ISSUE TITLE
device_state_attributes changes

### ISSUE THREAD

**Issue by ijustlikeit** [fwestenberg/reolink_dev#399]
Logger: homeassistant.helpers.entity
Source: helpers/entity.py:549
First occurred: 3:14:14 PM (8 occurrences)
Last logged: 3:15:35 PM

Entity camera.xxx (<class 'custom_components.reolink_dev.camera.ReolinkCamera'>) implements device_state_attributes. Please report it to the custom component author.

Looks like device_state_attributes needs to be changed to extra_state_attributes in HA 2021.12.0+.

**Comment by cpainchaud** [comment]
Please try 0.46
