### ISSUE TITLE
RLC-520A unexcepted error 

### ISSUE THREAD

**Issue by MiAutomations** [fwestenberg/reolink_dev#406]
Hello 

I'm  facing this issue, when I try to added this Camera over this Integration I have other models work without any problems 

![image](https://user-images.githubusercontent.com/47602733/145898111-3a210363-1054-449c-974b-b69723282e5f.png)

I already try with HHTPS and without checked, problem persiste  

 - Home Assistant version -> core-2021.12.1
 - Reolink camera model -> RLC-520A
 - Camera firmware number -> v3.1.0.598_21091300

**Additional context**
The camera is working well over the Reolink app in the android system also over the Windows APP and also over the RTSP or Onvif Integrations in The HA 

Please let me know if you need any further more information in order to try solve this issue ?

Thank you for your support and best regards

**Comment by kavemang** [comment]
Ive had this issue for about a month with an RLC-520 and an RLC-410, both are POE, my wifi reolink cam continues to work normally

**Comment by cpainchaud** [comment]
Please have a look here https://github.com/fwestenberg/reolink_dev/blob/master/TSHOOT.md to enable logging and share your HA logs

**Comment by MiAutomations** [comment]
Sorry for the late replay 

I found the issue, is related to the firmware Update of the camera that was changed my network settings of the camera  in this menu, after enable the issue is solved.  

![image](https://user-images.githubusercontent.com/47602733/150643484-89db59d3-d84b-4fc5-bf35-1180b09fe630.png)

Thank you for your support !! and best regards
