### ISSUE TITLE
Reolink RLC-520A, motion sensors

### ISSUE THREAD

**Issue by garry0garry** [fwestenberg/reolink_dev#419]
Reolink RLC-520A platform IPC_523128M5MP

Firmware v3.1.0.764_21121700 (beta)
All motion sensors are unavailable. 

Firmware v3.0.0.494_21073000 (last official)
All motion sensors are unavailable. 

Firmware v3.0.0.177_21012100
The "Person detected" sensor is **always off**. 

Do you need any logs? 

UPD. Firmware v3.0.0.494_21073000 (last official) - No problem. After a while, the sensors started working. Sorry!

**Comment by milandzuris** [comment]
Same last 4 months
