### ISSUE TITLE
Detected I/O inside event loop

### ISSUE THREAD

**Issue by jjwBullfrog** [fwestenberg/reolink_dev#43]
I repeatedly (thousands of times) get this error in the HA logs. I noticed it after going to 0.110.1. I'm not sure if it was there before.

Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for reolink_dev doing I/O at custom_components/reolink_dev/ReolinkPyPi/camera.py, line 272: response = requests.post(self._url, data=json.dumps(body), params=param)
Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for reolink_dev doing I/O at custom_components/reolink_dev/ReolinkPyPi/camera.py, line 270: response = requests.get(self._url, params=param, stream=stream)

Here is my system:

arch | x86_64
-- | --
chassis | vm
dev | false
docker | true
hassio | true
host_os | HassOS 3.13
installation_type | Home Assistant
os_name | Linux
os_version | 4.19.115
python_version | 3.7.7
supervisor | 222
timezone | America/Chicago
version | 0.110.1
virtualenv | false

What does it mean?

**Comment by fwestenberg** [comment]
Are you sure you have the custom Reolink component to the latest version? Should be solved.

**Comment by MattiasC** [comment]
I am not seeing this with version 0.3 of the component, could probably be closed.
