### ISSUE TITLE
Failed to connect with latest firmware

### ISSUE THREAD

**Issue by SkipXtian** [fwestenberg/reolink_dev#437]
Just updated the firmware and the integration now fails to connect.
It was connected before the update and no other changes were made to HA/network.
I've tried removing and re adding the integration and devices and the story is the same with both camera's I updated.

Model: RLC-820A
Build No. build 21121701
Hardware No. IPC_523128M8MP
Config Version v3.1.0.0
Firmware Version v3.1.0.764_21121701
Details IPC_523128M8MPS18E1W01100000001

**Comment by SkipXtian** [comment]
Can confirm reverting back to firmware version v3.0.0.494_21073001 makes everything work as it should.

**Comment by cpainchaud** [comment]
Hi,

 What were the error messages? Also remember that new firmware disables HTTP (leaves HTTPS open only) and RTSP+ONVIF by default, you need to turn them on again manually.

**Comment by mvbl** [comment]
I have the same problem, but I solved it.
If you use reolink application, you have to update it too, otherwise you won't see new settings (switches for protocols). HTTP and rtsp are indeed disabled by default.

You can notice this by going to port 80 in the settings through the browser.

Try it, it worked for me.

**Comment by ijustlikeit** [comment]
Thanks mvbl for your post!  I was using the Win 10 Reolink client and although it looks the same as the browser sign-in it doesn't have the  settings for enabling protocols.  I don't know why Reolink client has this inconsistency...just another of those gotchas.

So use the browser method and not the Win 10 client and will work for you.

**Comment by SkipXtian** [comment]
That was my issue, Thanks mvbl. I was using the app and couldn't find those settings anywhere.
Port 80 in the browser, Network settings -> Advanced -> Port settings, enabled the above and all started working.
Talk about confusing consistences.
