### ISSUE TITLE
HTTPS error - DH_KEY_TOO_SMALL

### ISSUE THREAD

**Issue by nrodday** [fwestenberg/reolink_dev#459]
Hi,

When trying to integrate a ReoLink C2 Pro, firmware version v2.0.0.477_19071504, I am getting the following error for SSL enabled connections:

ssl.SSLError: [SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1129)
aiohttp.client_exceptions.ClientConnectorSSLError: Cannot connect to host 192.168.2.87:443 ssl:default [[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1129)]

Since I cannot find any firmware version that is more recent than the current one, I am assuming that I am using the latest version. My HA is running on Home Assistant 2022.2.9.

Thanks,
Nils

**Comment by cpainchaud** [comment]
disable SSL and use Port 80. Yet your firmware number makes me believe this integration may never work for you

**Comment by nrodday** [comment]
Thanks for your reply. The updated firmware I got from the Reolink suport allows for SSL enabled connections and the error is gone.
