### ISSUE TITLE
E1 Pro question

### ISSUE THREAD

**Issue by qwik3r** [fwestenberg/reolink_dev#460]
I read that the E1 pro is not supported, but if it's connected via NVR would it then work, or just not at all?

**Comment by cpainchaud** [comment]
no one knows with this setup may be

**Comment by qwik3r** [comment]
> 

I'm sorry, what?

**Comment by cpainchaud** [comment]
no one answered because no one has the same setup

**Comment by qwik3r** [comment]
Gotcha. I was hoping that the creator of the integration would answer to confirm if it definitely does not work.
