### ISSUE TITLE
Error when adding Reolink RLC-820A

### ISSUE THREAD

**Issue by gdeuss** [fwestenberg/reolink_dev#463]
Getting the following integration error when attempting to add my first Reolink Camera to Home Assitant

Please let me know if I missed any info required to review this, I am not sure what else you may need to review. Running Home Assistant Core 2022.3.3 with Supervisor 2022.3.2 on HA OS 7.4 with Reolink V0.50 

![image](https://user-images.githubusercontent.com/95149025/157145522-78ff95d8-3373-4f5a-9a50-fe7ef4583084.png)

Obviously, the IP and the username password must be ok

![image](https://user-images.githubusercontent.com/95149025/157146046-9af1ca40-7637-492a-b1f0-f47fb44809f4.png)

![image](https://user-images.githubusercontent.com/95149025/157146475-65bca3ed-0746-4445-93a8-59c8ce14b321.png)

**Comment by klu03rl** [comment]
did you have this issue after upgrading the firmware?

**Comment by gdeuss** [comment]
No, never was able to connect. The firmware it shows on my setup is currently v3.0.0.494. It tells me that is the latest but when checking the Reolink website that latest seems to be v3.1.0.764. 
If you want me to use a specific version, let me know, happy to try. Trouble is, that is only one of 4 different cameras I use ☹

**Comment by gdeuss** [comment]
> No, never was able to connect. The firmware it shows on my setup is currently v3.0.0.494. It tells me that is the latest but when checking the Reolink website that latest seems to be v3.1.0.764. If you want me to use a specific version, let me know, happy to try. Trouble is, that is only one of 4 different cameras I use ☹

**Comment by gdeuss** [comment]
Just used the same camera type with integration v3.1.0.764. with the following result see below. Different but this time it can not even connect to the camera. No entry in the log for that time. It shows port 443 once the msg appears but I actually use port 80 with HTTPS disabled. With firmware v3.0.0.494 using port 80 with HTTP only or port 443 with HTTPS disabled produces the same result  

![image](https://user-images.githubusercontent.com/95149025/157337854-893d4616-d8b8-4a01-a318-11c49f7db730.png)

**Comment by cpainchaud** [comment]
Integration won't work with 2022.3 HA until I (or someone else) submits a patch. I need to find some time to work on it this week.

**Comment by gdeuss** [comment]
Thanks, Christophe, I assume that would apply to all Reolink camera types, correct?

**Comment by cpainchaud** [comment]
All fo them, HA has changed their APIs so it requires a fix somewhere to cope with that general change

**Comment by gdeuss** [comment]
closed in error, the issue is still pending HA API patch per cpainchaud

**Comment by cpainchaud** [comment]
please try 0.51 , now please note that if you keep mixing internal non-HTTP with external HTTPS address, it's not supported by HomeAssistant themselves

**Comment by gdeuss** [comment]
@cpainchaud @
Did some more testing with another camera model RLC-510WA and it looks like the remaining issues with the video integration are related to the .764 updates on the cameras. When I rolled back the camera firmware on hat camera to .494 the camera vidoe feed started working instantly.
The other two remaining camera types I have are RLC-823A and RLC-1212A. Neither has previous firmware available. They are new camera models and I can not roll them back. 
Is it possible that Reolink made some changes to their API with their .764 and later updates that the current Reolink .51 has not yet accounted for?
There is s separate but possibly related issue with the sensor integration of all cameras and I have not done any search for that issue yet and it has possibly been reported already. The sensor values got to "unavailable" after a while if you log out of HA and they will stay unavailable until to log back into HA. They will start updating again shortly after you log in and stay available as long as HA has an active login session. I may report that separately as a new issue and close this if you think I should do that.

**Comment by gdeuss** [comment]
@cpainchaud 
I am closing this issue. The original issue was solved by your Reolink 0.51 update. However, the issue with camera integration now seems to be the Reolink firmware .764 does not work with Reolink integration 0.51

**Comment by gdeuss** [comment]
No, never was able to connect. The firmware it shows on my setup is currently v3.0.0.494. It tells me that is the latest but when checking the Reolink website that latest seems to be v3.1.0.764.
If you want me to use a specific version, let me know, happy to try. Trouble is, that is only one of 4 different cameras I use ☹

Gustav Deuss
GRD Energy, Inc.
1 Avenue of the Palms, Suite 10C
San Francisco, CA 94130
O 415 891 8824
M 650 291 2569
