### ISSUE TITLE
switches are not available when cam is behind NVR

### ISSUE THREAD

**Issue by physi** [fwestenberg/reolink_dev#493]
**Describe the bug**
When I attach my cam RLC-812A to the Reolink NVR RLN16-410
by Reolink
Firmware: v3.0.0.148_21100910

I get no switches, i.e turn lights on, etc. I get only 6 entities (motion detections).

When I connect the same cam directly to HA it shows all switches (16 entities) and motion detections as well.

**Expected behavior**
I want to get all entities, even when connected to the NVR.
**Screenshots**

**Environment:**

**Additional context**

Is this a known bug, or did I misconfigured something?

**Comment by Siegfrost** [comment]
I'm also observing the same behavior.
Only Stream and Sensors detected in HA

RLC-812A
Firmware: v3.1.0.920

RLN16-410 NVR
Hardware No. H3MB18
Firmware: v3.0.0.148_21100910

**Comment by Aturner4444** [comment]
I am having the same issue, switches used to work perfectly, I was able to turn the push notifications on and off depending on the state of my alarm, however since I updated to the latest HA the switches have disappeared. I hope they come back as this was extremely useful.

**Comment by helpdt** [comment]
Hi, thanks for this really usefull integration. 
Right now I'm also observing the same behavior.
Only Stream and Sensors detected in Homeassistant since Core version 2022.5.1. Before I updated all things work really fine. 

Reolink: E1 outdoor
FW: v3.0.0.460_2107140

**Comment by Neokeek** [comment]
yes, with out NVR i get 13 Entitys with only 3, no person detection only motion. Hope this can be fixed

**Comment by Krishomeas** [comment]
I'm experiencing the same with 2x RLC-823A cameras behind 8ch NVR

**Comment by mnpg** [comment]
For all of you, take a look at this information, you'll better understand :
https://www.reddit.com/r/reolinkcam/comments/uvgw9l/reasons_to_run_cameras_through_a_poe_switch/

**Comment by Krishomeas** [comment]
> For all of you, take a look at this information, you'll better understand : https://www.reddit.com/r/reolinkcam/comments/uvgw9l/reasons_to_run_cameras_through_a_poe_switch/

Thanks for your suggestion- it worked for me. I placed the poe switch between the router and NVR and plugged the cameras into the switch. The NVR instantly found the cameras on the network and continued the recording schedule I previously set. All of the switches for the camera entities are also now appearing in HA, plus the option to record a time lapse has returned and integration into Google Home (in my scenario) is now possible. This setup was exactly what I was looking for, it's just a shame these features and switches aren't supported natively through the NVR.

**Comment by mnpg** [comment]
> it's just a shame these features and switches aren't supported natively through the  #NVR.
I do agree. The API isn't the same through all the cameras. 
Reolink must have a effort to have a stable and uniform API, that commands work with all the cameras (when they are missing, add it). I enrage everytime when i want to make programs with these cams, AI and not-AI
