### ISSUE TITLE
Unexpected error

### ISSUE THREAD

**Issue by Smartandsec** [fwestenberg/reolink_dev#494]
I first installed the reolink integration with a RLC-823A but I wanted a wireless version so I got the RLC-523WA after I got the wireless version I removed the reolink integration and tried to install it again but now I am getting an "Unexpected error" in the integration and it won't let me setup the integration...

Logs:
Logger: custom_components.reolink_dev.config_flow
Source: config_entries.py:1258
Integration: Reolink IP camera ([documentation](https://github.com/fwestenberg/reolink_dev), [issues](https://github.com/fwestenberg/reolink_dev/issues))
First occurred: 11:48:45 AM (1 occurrences)
Last logged: 11:48:45 AM

Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/reolink_dev/config_flow.py", line 79, in async_step_user
    self._abort_if_unique_id_configured()
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1258, in _abort_if_unique_id_configured
    raise data_entry_flow.AbortFlow("already_configured")
homeassistant.data_entry_flow.AbortFlow: Flow aborted: already_configured

**Comment by therin** [comment]
I have the same issue - how did you ended up fixing this?

**Comment by Smartandsec** [comment]
I went through my laptop and found out that the Reolink was disabled, I enabled it and removed it and then redid the whole thing again and it worked, good luck
