### ISSUE TITLE
[FR] Possible to select other scenes

### ISSUE THREAD

**Issue by hapklaar** [fwestenberg/reolink_dev#503]
It looks like it isn't possible yet to select a scene that is configured on the camera. Would it be possible to add this functionality? The goal is to be able to select different scenes via automation.

**Comment by mnpg** [comment]
Thexscene mode is specific to the smarthone applicatiob. It can't be managed through the Reolink API. The only way is you have is to create an automation via HA, switching On or Off the switches that control the different functionalities of the surveillance mode (Rec, Email, Ftp, AudioAlarm and Push)
