### ISSUE TITLE
RLC-811a fails after firmware update 3.0 -> 3.1

### ISSUE THREAD

**Issue by Phadeguy** [fwestenberg/reolink_dev#508]
**Describe the bug**
The integration fails with "unexpected error" after upgrading to firmware 3.1.0.956_22042008.  The camera still works correctly with the native Reolink app and direct browser login to the device. 

**To Reproduce**
1. Upgrade to firmware 3.1
2. Observe the camera working correctly with the native Reolink app and direct browser login.
3. Any existing Home Assistant integration will now fail.
4. Adding the device with a new "add integration" fails with an error message "unexpected error".

**Expected behavior**
Integration to work as it did with firmware 3.0

**Screenshots**
No screenshot is necessary.

**Environment:**
Please provide useful information about your environment, like:
 - Home Assistant version: 2022.5.5
 - Reolink camera model: RLC-811a
 - Camera firmware number: 3.1.0.956_22042008

**Additional context**
You're still awesome!!

**Comment by ptyers** [comment]
Immediately after attempting to add integration check homeassistant.log and see if there is any related message. Will aid in diagnosis.

**Comment by Phadeguy** [comment]
Thank you for the reply!

I checked and I wasn't on version 0.54 of the Reolink integration.  Upgrading to that version fixed the connection issue.

However, it seems to have introduced a new issue:  Motion sensors are no longer responding; they trigger the native Reolink app but they do not trigger within Home Assistant.   I will submit a new report for this issue.

Thanks again!!
