### ISSUE TITLE
Snapshot requires login first

### ISSUE THREAD

**Issue by homietw** [fwestenberg/reolink_dev#52]
While the live stream in lovelace works, the 
camera.snapshot Service constantly fails to create snapshot images, the result is:

`[
   {
      "cmd" : "Snap",
      "code" : 1,
      "error" : {
         "detail" : "please login first",
         "rspCode" : -6
      }
   }
]`

The live stream preview (lovelace) isn't most of the time showing an image as well, but when opening the stream in homeassistant, the stream shows the live video.

**Comment by homietw** [comment]
Seems to be a session related problem? After restarting homeassistant, the camera.snapshot Service works for some time until it breaks again.

**Comment by IvanPenyaHuguet** [comment]
I can't reproduce it, it works fine for me in the last version. Anything special happens to break it?
