### ISSUE TITLE
HACS install -  no `install` button

### ISSUE THREAD

**Issue by mtoka** [fwestenberg/reolink_dev#532]
**Describe the bug**
I followed HACS installation path. Installing HACS itself beforehand with no issue.
While following steps for installing reolink_dev integration I successfully get up to point "**7. click add**"
Problem is at step "**8.click install**" because I can't see it anywhere.
Attached screenshot after step **7**
Restarting HA nor instance doesnt help.
Same status is visible for this integration.

I can click **Dismiss** but then integration dissapears. Please see second screenshot No2.

If I in top right corner open "3 dots" I can see this integration on the list. PLease see screenshot No3.

Any idea where have I made mistake?

**Screenshots**
No1.
After performing step **7. click add** & restarting
<img width="1043" alt="Screenshot 2022-07-15 at 14 45 44" src="https://user-images.githubusercontent.com/18126201/179225627-8ca8754f-719a-4d78-9256-cedc5d8c5b49.png">

No2.
After clicking on **Dismiss**
<img width="1063" alt="Screenshot 2022-07-15 at 14 48 04" src="https://user-images.githubusercontent.com/18126201/179225988-0708dc5e-aaf5-4dab-843e-43532874d592.png">

No3.
<img width="469" alt="Screenshot 2022-07-15 at 14 55 38" src="https://user-images.githubusercontent.com/18126201/179227255-87d0e3ea-ebc4-4f8a-9d21-056fc57bb135.png">

**Environment:**
Home Assistant 2022.7.4
Supervisor 2022.07.0
Operating System 8.2
Frontend 20220707.0 - latest

**Comment by oneseventhree** [comment]
It looks like you already installed it. You just need to set it up in Integrations. Watch this video:
https://www.youtube.com/watch?v=8DhfZefpJCY&ab_channel=MarkWattTech
It helped me a lot
