### ISSUE TITLE
AI detection info fails after FW upgrade to Firmware: v3.1.0.920_22040613 

### ISSUE THREAD

**Issue by wordblind** [fwestenberg/reolink_dev#535]
**Describe the bug**
Motion detection and AI  functionality of my RLC812A such as Person / Car / Pet detection stooped working after upgrading FW to  Firmware: v3.1.0.920_22040613 
I get person detentions in the app but not in home assistant. 

**To Reproduce**
Upgrade FW 

**Expected behavior**
Change in of detection 

**Screenshots**
At 5:40 i upgraded the firmware, before we can see alot of detection, and after i get 0 detections even tho i get infront of the camera.  
![image](https://user-images.githubusercontent.com/12498095/179839915-db234e94-b4c3-4486-866e-b1596780f561.png)

**Environment:**
Please provide useful information about your environment, like:
 - Home Assistant version Home Assistant 2022.4.5
 - Reolink camera model RLC812A
 - Camera firmware number: v3.1.0.920_22040613 

**Additional context**
Issue apers after upgrade to v3.1.0.920_22040613

**Comment by mnpg** [comment]
Take a look at the previous post #554 : https://github.com/fwestenberg/reolink_dev/issues/534

**Comment by wordblind** [comment]
Resolution - Open ports under Settings / Network / Advanced
