### ISSUE TITLE
reolink_ dev is requesting info all the time

### ISSUE THREAD

**Issue by Letalis** [fwestenberg/reolink_dev#57]
I noticed that my HA installation was slowing down the network and when analyzing it some more I noticed that the reolink_dev integrations is pulling/requesting data all the time.
Even though I have extended that scan intervall the integration is pulling 6-8Mb/seconds all the time.

when I turn of the integration the traffic stops to its related to the integration.

Is there a way to stop this behaviour?

![image](https://user-images.githubusercontent.com/1169121/89014805-5d859c00-d316-11ea-99c7-e987ae39a554.png)

Im using it against my NVR.

`camera:
- platform: reolink_dev
  name: garage
  host: 10.10.10.111
  username: !secret reolinkusr
  password: !secret reolinkpw
  scan_interval: '00:05:00' 
  channel: 0
- platform: reolink_dev
  name: pool
  host: 10.10.10.111
  username: !secret reolinkusr
  password: !secret reolinkpw
  scan_interval: '00:05:00' 
  channel: 1
- platform: reolink_dev
  name: altan
  host: 10.10.10.111
  username: !secret reolinkusr
  password: !secret reolinkpw
  scan_interval: '00:05:00' 
  channel: 2
- platform: reolink_dev
  name: baksida
  host: 10.10.10.111
  username: !secret reolinkusr
  password: !secret reolinkpw
  scan_interval: '00:05:00' 
  channel: 3

`

**Comment by fwestenberg** [comment]
What is your HA version?

**Comment by Letalis** [comment]
0.112.4

**Comment by fwestenberg** [comment]
On the latest HA version, is this still a problem?
