### ISSUE TITLE
Motion states could not be queried from API

### ISSUE THREAD

**Issue by cloudbr34k84** [fwestenberg/reolink_dev#578]
Logger: custom_components.reolink_dev.binary_sensor
Source: custom_components/reolink_dev/binary_sensor.py:125
Integration: Reolink IP camera ([documentation](https://github.com/fwestenberg/reolink_dev), [issues](https://github.com/fwestenberg/reolink_dev/issues))
First occurred: 7:44:25 am (1 occurrences)
Last logged: 7:44:25 am

Motion states could not be queried from API

It appears one of my cameras is not showing Any Motion
Not Available
![image](https://user-images.githubusercontent.com/58960644/193735846-ab03b17d-ea7d-4477-a0a3-d760dfa25dab.png)

Available
![image](https://user-images.githubusercontent.com/58960644/193735890-6c74a070-b039-4e70-b633-a3ee479f8412.png)

**Comment by cloudbr34k84** [comment]
Logger: custom_components.reolink_dev
Source: helpers/update_coordinator.py:151
Integration: Reolink IP camera ([documentation](https://github.com/fwestenberg/reolink_dev), [issues](https://github.com/fwestenberg/reolink_dev/issues))
First occurred: 9:05:58 am (3 occurrences)
Last logged: 9:05:58 am

Timeout fetching reolink.Backyard Camera.motion_states data
Timeout fetching reolink.Frontyard Camera.motion_states data
Timeout fetching reolink.Driveway Camera.motion_states data

**Comment by JimStar** [comment]
This was already fixed some time ago here: [https://github.com/JimStar/reolink_cctv](https://github.com/JimStar/reolink_cctv)

**Comment by cloudbr34k84** [comment]
Ok, so why is it still happening. Im still getting the log error as of 3 mins ago
Logger: custom_components.reolink_dev
Source: helpers/update_coordinator.py:151
Integration: Reolink IP camera ([documentation](https://github.com/fwestenberg/reolink_dev), [issues](https://github.com/fwestenberg/reolink_dev/issues))
First occurred: 6:07:13 pm (3 occurrences)
Last logged: 6:07:13 pm

Timeout fetching reolink.Backyard Camera.motion_states data
Timeout fetching reolink.Frontyard Camera.motion_states data
Timeout fetching reolink.Driveway Camera.motion_states dat

**Comment by JimStar** [comment]
Did you follow my link and read the README?..

**Comment by cloudbr34k84** [comment]
im skimming through now..
Fixed the often-happened "Unavailable" status of detection sensors.,

**Comment by cloudbr34k84** [comment]
OHHHH ITS A NEW hacs! MY BAD!

**Comment by cloudbr34k84** [comment]
Yeah sorry mate! :(
