### ISSUE TITLE
E1 Zoom: 'enable' in "GetAlarm" response is set to 1602

### ISSUE THREAD

**Issue by gman-php** [fwestenberg/reolink_dev#59]
Hey there,

I was wondering why the motion detection for my E1 Zoom is not working in Home Assistant, neither does en/disabling it work (also made a post here: https://community.home-assistant.io/t/reolink-dev-cant-get-motion-detection-to-work-e1-zoom/217271).

I dug a bit and logged the response of `get_settings` and turns out that `data["value"]["Alarm"]["enable"]` is set to 1602 for my E1 Zoom!?

So an easy fix was replacing the check here: https://github.com/fwestenberg/reolink/blob/master/custom_components/reolink_dev/ReolinkPyPi/camera.py#L113
with `if (data["value"]["Alarm"]["enable"] >= 1):`.
This fixed the motion detection in HA: binary_sensor is triggered and the motion detection switch is also set to `on`.

However, what still doesn't work is disabling the motion detection and that's where I'm stuck a bit:

I logged the response of `set_motion_detection` and it looks fine:
```
[
   {
      "cmd" : "SetAlarm",
      "code" : 0,
      "value" : {
         "rspCode" : 200
      }
   }
]
```

But when `get_settings` is called right after, `data["value"]["Alarm"]["enable"]` is still set to 1602... Is something wrong with my E1 Zoom? Any other people with that camera with the same issue?

Bought the camera a few days ago, device info attached as screen shot from the Reolink app:
![Screenshot_20200810_220436_com mcu reolink_2](https://user-images.githubusercontent.com/3090131/89865933-eae6ad00-dbae-11ea-9eef-80756c9eb656.jpg)

Also attached an example response of `get_settings`: [get_settings.txt](https://github.com/fwestenberg/reolink/files/5053107/get_settings.txt)

Any ideas?

Greetings,

Andy!

**Comment by gman-php** [comment]
Another thing I realized: I can't even find a way ti disable motion detection in the app or on the web portal. I can set sensitivity schedules, but no way to disable motion detection :/

How does it work for other camera models?

**Comment by fwestenberg** [comment]
What response code do you get when there is no motion?

**Comment by gman-php** [comment]
You mean from `GetMdState`? Still 200.

That's how they look like:

If there is *no* motion:
Status: 200
Body:
```
[{
	"cmd": "GetMdState",
	"code": 0,
	"value": {
		"state": 0
	}
}]
```

If there *is* motion:
Status: 200
Body:
```
[{
	"cmd": "GetMdState",
	"code": 0,
	"value": {
		"state": 1
	}
}]
```

The `get_settings` looks completely the same in both cases (like the example I already attached in the first post), also always 200.

I've set up my Postman now to make calls to the camera easily. I will test around a bit and see if I find something odd :/

**Comment by gman-php** [comment]
Hrrmmm, according to this support page, there is no real way for non-battery powered cameras to turn motion detection off!? They tell you to disable the whole zone :D

https://support.reolink.com/hc/en-us/articles/360006990333-How-to-Disable-Motion-Detection

**Comment by gman-php** [comment]
Yeah, setting the whole detection zone (`data["value"]["Alarm"]["scope"]["table"]`) to 0 of course works: That will disable motion detection, because it voids the whole detection zone.

But `data["value"]["Alarm"]["enable"]` is still set to 1602! :D So there is no easy way to then detect that motion detection is disabled, except of checking that `data["value"]["Alarm"]["scope"]["table"]` is full of zeros :/

**Comment by gman-php** [comment]
(sorry for spamming ;) )

Ok, I made a hotfix for me / the E1 Zoom: https://github.com/gman-php/reolink/commit/4f0b6c365fe9ff703e2d75d20b0baa34d0f4ce21

* Motion detection state properly works now
* En/Disabling motion detection also

Known issues / things-to-check:
* It always fully en- or disabled the motion zone. If you have any motion zone set, it will wipe / overwrite it when en/disabling motion detection
* I changed the check for motion detection from `== 1` to `>= 1`. I don't know what other cameras return if motion detection is disabled. I'm guessing they return 0, so it's probably fine. But if they also return something weird / larger then 1 there, this check would fail.

However, I leave the real fix up to you / appreciate your feedback and can submit a PR then :)

Greetings,

Andy!

**Comment by pipip** [comment]
I have the same problem with my E1 Zoom. Thank you for your investigation and update posts.
Weired thing: it used to work for me

**Comment by fwestenberg** [comment]
Please check v0.8. Should be fixed!

**Comment by pipip** [comment]
hmm, I don't have motion alerts on my two E1  Zoom with the update to v0.8
the gman-php fix worked...

**Comment by fwestenberg** [comment]
What kind of motion detection do you expect? With v0.8 there should be a binary sensor available in HA with motion detection. From there, you can automate any kind of motion alerts... Is this what you need?

**Comment by fwestenberg** [comment]
... and the service camera.enable_motion_detection / camera.disable_motion_detection enables or disables the binary switch reaction.

**Comment by pipip** [comment]
@fwestenberg
thanks for the fast reply. 
I do have the automatically created binary sensor. This shows "clear" the entire time, even though there is motion (the reolink app also displays this). I called the service (enable motion detection) just to make sure but that did not change anything.
With the previous version I had the same behaviour and used the fix (repo from gman-php) above which made the motion detection work.

**Comment by fwestenberg** [comment]
The motion detection now works with the Onvif events, does your camera support that? Perhaps you can also post the response from this [Postman call](https://github.com/fwestenberg/reolink_dev/issues/89#issuecomment-742373013)

**Comment by pipip** [comment]
Yes, the E1-Zoom does support Onvif. I did not add the camera via the Home Assistant Onvif integration, only via Reolink_dev...
Result of Postman call: [Reolink_E1Zoom.txt](https://github.com/fwestenberg/reolink_dev/files/5674002/Reolink_E1Zoom.txt)

**Comment by fwestenberg** [comment]
This is correct, you don't need to do anything with the onvif integration. Not depending on it either. You could set the logging for reolink_dev to debug. If you add it again, it will show more details. Can you please try this? Thanks!

**Comment by pipip** [comment]
I don't see any relevant error... 
"Finished fetching reolink data..." goes on and on now. I triggered motion alerts during the time and checked parallel in Reolink app which displayed motion. The sensor in home assistant stays on clear. 

`2020-12-10T18:18:10.411817829Z 2020-12-10 19:18:10 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry E1-Zoom xxx for reolink_dev
2020-12-10T18:18:10.411878293Z   File "/config/custom_components/reolink_dev/__init__.py", line 174, in async_unload_entry
2020-12-10T18:18:10.411892615Z   File "/config/custom_components/reolink_dev/__init__.py", line 161, in unregister_webhook
2020-12-10T18:18:10.411903589Z AttributeError: 'ReolinkBase' object has no attribute 'data'
2020-12-10T18:18:36.394802780Z 2020-12-10 19:18:36 DEBUG (MainThread) [custom_components.reolink_dev] Finished fetching reolink data in 2.390 seconds
2020-12-10T18:18:42.833217835Z 2020-12-10 19:18:42 INFO (MainThread) [custom_components.reolink_dev.base] Host 192.168.x.xx subscribed successfully to webhook http://192.168.x.xx:8123/api/webhook/xxx
2020-12-10T18:18:44.247849118Z 2020-12-10 19:18:44 DEBUG (MainThread) [custom_components.reolink_dev] Finished fetching reolink data in 1.415 seconds
2020-12-10T18:19:38.314639903Z 2020-12-10 19:19:38 DEBUG (MainThread) [custom_components.reolink_dev] Finished fetching reolink data in 1.918 seconds `
