### ISSUE TITLE
Push notification

### ISSUE THREAD

**Issue by Cast-R** [fwestenberg/reolink_dev#635]
Hello,
I'm a beginer in Home Assistant. So I try to explain my issue.

We I launch the action "Activate or Desactivate push notification" I don't see any action on my camera configuation. Nevertheless, when I use the action for FTP this action works.

I use : 
-  Home Assistant 2023.3.6
- Trackmix POE Firmware : v3.0.0.1584_22120100
- 

Could you help me?
If you want more information don't hesitate.

Many thanks for your help!

**Comment by cpainchaud** [comment]
This is expected. Phone app Push notifications button only reflects the link between the camera and phone. Hass integration manipulates the global d

**Comment by Cast-R** [comment]
Thanks for you quick reply! It works fine.
