### ISSUE TITLE
Camera on port 82 instead of 80

### ISSUE THREAD

**Issue by magnushasselquist** [fwestenberg/reolink_dev#65]
Hi,
Is there a way I can configure this addon to support connecting to the camera on an other port than 80 (for http). 
(for streaming standard ports are ok for me, for now at least - but I guess they could be configurable also).
/Magnus

**Comment by fwestenberg** [comment]
At this moment integration connects to the camera on the default port. But for streaming, port numbers are read from your camera config (Network tab).

**Comment by fwestenberg** [comment]
Please check v0.8. Should be fixed!
