### ISSUE TITLE
HA Requires Reboot if the camera does not respond during start up

### ISSUE THREAD

**Issue by rednus** [fwestenberg/reolink_dev#66]
Hi, First of all, thank you so much for this plug in. Your work on this is highly appreciated. 

Could you please take a look at the issue below: 

I have four cameras using this plugin. During HA boot up and setting up entities, if a camera does not respond - that camera and its related entities are not setup. Usually this could be due to camera being slow or temp off network etc.  In this case in order to make this camera work, HA needs to be restarted. 

Is there a way, during boot up all entities are setup irrespective of connection to camera, and log a message that camera is not responding; then keep trying to connect every 5mins lets say. 

The main point is to avoid HA restart.

Thanks

**Comment by fwestenberg** [comment]
Please check v0.8. You can now reload from the Integrations page.
