### ISSUE TITLE
Error librav.rtsp

### ISSUE THREAD

**Issue by KameDomotics** [fwestenberg/reolink_dev#71]
Hi, from today in my HomeAssistant Log I have this issue (with a lot occurrences):

```suggestion

Logger: libav.rtsp
Source: components/stream/worker.py:214 
First occurred: 21:43:23 (16247 occurrences) 
Last logged: 21:53:44

RTP: PT=60: bad cseq c89a expected=fd4c
RTP: PT=61: bad cseq 5bd1 expected=9e05
RTP: PT=61: bad cseq 9e06 expected=5bd3
RTP: PT=60: bad cseq fd4d expected=c89c
RTP: PT=61: bad cseq 5bd4 expected=9e08

```

All cameras work fine in original Reolink app and even in HomeAssistant.

**Comment by KameDomotics** [comment]
Now it's 26542 occurrences, continuously increase.

**Comment by fwestenberg** [comment]
Did you already solve this? As far as I know, you are the only one with this issue. Also you can try the other streaming protocol.

**Comment by gregoryduckworth** [comment]
I’ve had this error before, it usually happens if you restart HA a few times within a short time frame, say 3 times within 20 minutes. 

Does a restart solve the issue?
