### ISSUE TITLE
Everything working fine except for streaming

### ISSUE THREAD

**Issue by jjpeet** [fwestenberg/reolink_dev#74]
Hi,
I just bought an NVR & 8 cameras are am setting them up using your add-on. Thanks for your work it's great!

Everything seems fine, except for one thing. When I click on the camera image on Lovelace, normally it was give me a pop up with a live stream of the camera but I get nothing. The popular appears, but it empty.

Is there anything I should check to get this going?

Thx
JP

**Comment by jjpeet** [comment]
Actually, it does work after 7 seconds. My other cameras (existing cameras of various types) start streaming instantly.
I've tried both main and sub streams, but do this wait thing.

I'm connected to my Reolink cams through NVR...

Thx
JP

**Comment by fwestenberg** [comment]
Please check v0.8. Please reopen if the issue still exists (and your connection to the camera is OK).
