### ISSUE TITLE
Infrared switch

### ISSUE THREAD

**Issue by Eddie46848** [fwestenberg/reolink_dev#78]
Hi noticed a issue when toggling Infrared on and off , it switches the display option for day and night.
The Infrared doesn't get toggled.

Thanks

**Comment by fwestenberg** [comment]
Hi, it gets fixed in the official release! Please be patient!

**Comment by fwestenberg** [comment]
Please check v0.8. Should be fixed!

**Comment by Eddie46848** [comment]
Hi
Thanks, yes everything is working fine now with v0.8.

Thanks
