### ISSUE TITLE
HACS Install No Longer Works

### ISSUE THREAD

**Issue by jjwBullfrog** [fwestenberg/reolink_dev#81]
Hi, great integration - I've been using it for a while.

However, HACS recently said a newer version was available, so I clicked to upgrade. What was weird was the version number had changed from something like V0.7 to V0.005. Anyways, it didnt work and in troubleshooting I uninstalled reolink and tried to reinstall it through the custom repositories per the instruction on this page. It doesn't work for me as the it says the repository file structure isn't valid. I tried the manual install, but the reolink_dev folder isn't part of the reolink-master.zip file.

Any ideas on what is going on here?

arch | x86_64
-- | --
chassis | vm
dev | false
docker | true
docker_version | 19.03.12
hassio | true
host_os | HassOS 4.16
installation_type | Home Assistant OS
os_name | Linux
os_version | 5.4.75
python_version | 3.8.6
supervisor | 2020.11.0
timezone | America/Chicago
version | 0.117.6
virtualenv | false

**Comment by fwestenberg** [comment]
I know, I move the repository. Please see the other issues about this. You can uninstall-reinstall. This should work. I'm moving this to the HA repository, pull request is opened already. ;-)

**Comment by jjwBullfrog** [comment]
Ok, that didnt work yesterday, but for some reason it works today. Back up and running!!
