### ISSUE TITLE
HassOS - "Repostitory structure for v008 is not compliant"

### ISSUE THREAD

**Issue by jjeremia** [fwestenberg/reolink_dev#82]
Tried to add your repository on my HassOS, but get this error. Maybe its not working with HassOS?

**Comment by fwestenberg** [comment]
Just be patient! I'm working on an official Home Assistant release. Hope the PR will be approved soon! I'll keep you posted, I'm sure it's worth waiting for!

**Comment by RestOp** [comment]
Hello,

no i gat the same but v009 ;-)))
Waiting, thanks a lot)

**Comment by fwestenberg** [comment]
Is fixed already.
