### ISSUE TITLE
Error that is only fixed by rebooting the camera

### ISSUE THREAD

**Issue by smugleafdev** [fwestenberg/reolink_dev#83]
Sometimes I go a few days with the camera working on my frontend, and other times I reset it five times in one day. This is the error I get, and it never resolves. Usually rebooting the camera solves it. Sometimes I have to reboot both the camera and HA.

Logger: custom_components.reolink_dev.camera
Source: custom_components/reolink_dev/camera.py:388
Integration: reolink_dev (documentation, issues)
First occurred: 10:35:49 PM (16 occurrences)
Last logged: 10:57:49 PM

Failed to reconnect with Reolink at IP 192.168.1.<XX>. Retrying in 60 seconds.

**Comment by fwestenberg** [comment]
Please check v0.8. If this still occurs, please reopen.
