### ISSUE TITLE
Allow empty password in Integration flow

### ISSUE THREAD

**Issue by Scope666** [fwestenberg/reolink_dev#88]
1 out of 5 of my RLC-410W's has a bug where it can't remember it's password.  It keeps reseting to blank.  Is it possible to allow an empty password in the integration flow?

**To Reproduce**
Next button won't appear unless you enter at least one character.

**Expected behavior**
Allow empty password.

**Environment:**
Please provide useful information about your environment, like:
 - Home Assistant version  0.118.5
 - RLC-410W
 - Latest FW

Thanks as always for everything that you do.    :-)

I'm on v0.8 that you just released today.

**Comment by fwestenberg** [comment]
I don't think an empty password is a good idea at all. Please fix the main cause: the camera. Perhaps you can reflash the firmware, or contact Reolink about this?

**Comment by Scope666** [comment]
I have, they sent me a replacement.  I'm still using this one because other than it remembering the password it works perfectly.  I hate to waste it just because of the password thing.  If there isn't an easy fix, don't worry about it.  I run Blue Iris, and lately I've been using it to feed HA, to keep the "strain" on the cameras down. I use your integration for the sensors / switches.

**Comment by fwestenberg** [comment]
If you really want this, please change the line `vol.Required(CONF_PASSWORD): str,` in custom_components/reolink_dev/config_flow.py to `vol.Optional(CONF_PASSWORD): str,`
