### ISSUE TITLE
Second Camera entities unavailable

### ISSUE THREAD

**Issue by rangulvers** [fwestenberg/reolink_dev#92]
**Describe the bug**
After updating to 0.8 via HACS only one camera works as it should (with 0.7 both worked fine)

The stream keeps breaking up and all entities for the camera are set to unavailable. 

**To Reproduce**
Connect the first camera -> works well
Connect the second camera -> has issues

**Expected behavior**
Both cameras should be added and all entities become available

**Screenshots**
![image](https://user-images.githubusercontent.com/5235430/101745297-7293e800-3acb-11eb-8e9f-705ecb90002f.png)

![image](https://user-images.githubusercontent.com/5235430/101745034-627c0880-3acb-11eb-8af9-72e4b55e4115.png)

**Environment:**

 - Home Assistant  Version
2020.12.6
 - Reolink camera model
RLC-511W
build no. build 20071004
FW v3.0.0.65_20071004

**Comment by fwestenberg** [comment]
This is strange. Are you sure the camera responds well?  I have two camera's running fine...

**Comment by rangulvers** [comment]
so far it has worked fine with version 0.7. But I will run some network checks to make sure this is not the issue. 

Both camera's are connect via wifi and are sitting 5 feed apart facing in different directions.

**Comment by rangulvers** [comment]
@fwestenberg I did some more tests. Network connection seems to be a little flaky so this can be a reason that the second camera is showing issues. Still strange that it worked before. 

For testing I removed the second camera from home assistant just to make sure. After removing it and restarting everything i get the following error message in the logs. This should not be there since this is the removed camera

![image](https://user-images.githubusercontent.com/5235430/101753070-855deb00-3ad2-11eb-8470-641d306b6352.png)

**Comment by fwestenberg** [comment]
How long after removing the camera is this error showing up? Might be the stream from HA still trying to open.

**Comment by rangulvers** [comment]
I still saw the log entry about 10min after I have removed everything and restarted HA. It is gone now. 

I will keep you posted with more testings around this issue. Setup a second HA to test on a fresh install

**Comment by rangulvers** [comment]
It seems like the latest branch https://github.com/fwestenberg/reolink_dev/tree/NVR_and_bug_fixes also fixed the connection issue. This would point everything to the https vs http issue. I even turned off two AP to really stretch the wireless signal but everything holds up just fine
