### ISSUE TITLE
Clicking on camera feed gives notification of invalid login

### ISSUE THREAD

**Issue by Dutch317** [fwestenberg/reolink_dev#95]
**Describe the bug**
Using a Picture Glance Card for the camera view, when it is clicked on or camera view is changed to live, I get a notification of
invalid login attempt from the ip address of the computer being used. (banned after 3 times).

**To Reproduce**
Set up the Picture Glance Card Configuration for the reolink camera and ether click on the picture card or change the configuration to live

**Expected behavior**
Should open the live view?

**Environment:**
HA Version | 0.118.5
Installation Type | Home Assistant OS
Development | false
Supervisor | true
Docker | true
Virtual Environment | false
Python Version | 3.8.6
Operating System Family | Linux
Operating System Version | 5.4.77

 - Reolink camera model
RLC-410-5MP
 - Camera firmware number
v3.0.0.65_20071000

**Comment by Dutch317** [comment]
After some more digging I found the error in the logs:

2020-12-13 10:12:52 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 277, in preload_stream
request_stream(hass, source, keepalive=True, options=camera.stream_options)
File "/usr/src/homeassistant/homeassistant/components/stream/__init__.py", line 47, in request_stream
raise HomeAssistantError("Stream integration is not set up.")
homeassistant.exceptions.HomeAssistantError: Stream integration is not set up.

Not sure how it happened but the stream component was missing from the config file. After adding and rebooting it is back up and working fine.

**Comment by fwestenberg** [comment]
Did you put 

`ffmpeg:`

in your confuguration.yaml?

**Comment by fwestenberg** [comment]
This should fix the issue, please reopen or add comment if not. Thanks.
