### ISSUE TITLE
Stream Reolink to chrome cast

### ISSUE THREAD

**Issue by rangulvers** [fwestenberg/reolink_dev#98]
It is not a bug but more of a general question. 

Have you ever managed to stream the Reolink camera to a Google chromecast? I have been playing around with this but sofar no luck. The camera.stream component is able to trigger my cast but it fails and nothing happens.

**Comment by fwestenberg** [comment]
The camera uses the default HA stream option. So it took me 10 seconds at Google and 1 minute to figure out it actually worked like this:

`Service: camera.play_stream`

and pass the data:

```
entity_id: camera.frontdoor
media_player: media_player.chromecast
```

**Comment by rangulvers** [comment]
I know how to set it up. My issue is that it never really loads the stream. I have found other forums that state this might be an issue with the h.264 stream from the camera. 

That's why I asked if you have ever tried this option and really get it to work
